const PROGRAM = [
    { type: 'set', register: 'i', value: 31 },
    { type: 'set', register: 'a', value: 1 },
    { type: 'mul', register: 'p', value: 17 },
    { type: 'jgz', value: 'p', offset: 'p' },
    { type: 'mul', register: 'a', value: 2 },
    { type: 'add', register: 'i', value: -1 },
    { type: 'jgz', value: 'i', offset: -2 },
    { type: 'add', register: 'a', value: -1 },
    { type: 'set', register: 'i', value: 127 },
    { type: 'set', register: 'p', value: 464 },
    { type: 'mul', register: 'p', value: 8505 },
    { type: 'mod', register: 'p', value: 'a' },
    { type: 'mul', register: 'p', value: 129749 },
    { type: 'add', register: 'p', value: 12345 },
    { type: 'mod', register: 'p', value: 'a' },
    { type: 'set', register: 'b', value: 'p' },
    { type: 'mod', register: 'b', value: 10000 },
    { type: 'snd', register: 'b' },
    { type: 'add', register: 'i', value: -1 },
    { type: 'jgz', value: 'i', offset: -9 },
    { type: 'jgz', value: 'a', offset: 3 },
    { type: 'rcv', value: 'b' },
    { type: 'jgz', value: 'b', offset: -1 },
    { type: 'set', register: 'f', value: 0 },
    { type: 'set', register: 'i', value: 126 },
    { type: 'rcv', value: 'a' },
    { type: 'rcv', value: 'b' },
    { type: 'set', register: 'p', value: a },
    { type: 'mul', register: 'p', value: -1 },
    { type: 'add', register: 'p', value: 'b' },
    { type: 'jgz', value: 'p', offset: 4 },
    { type: 'snd', register: 'a' },
    { type: 'set', register: 'a', value: 'b' },
    { type: 'jgz', value: 1, offset: 3 },
    { type: 'snd', register: 'b' },
    { type: 'set', register: 'f', value: 1 },
    { type: 'add', register: 'i', value: -1 },
    { type: 'jgz', value: 'i', offset: -11 },
    { type: 'snd', register: 'a' },
    { type: 'jgz', value: 'f', offset: -16 },
    { type: 'jgz', value: 'a', offset: -19 },
];

const SAMPLE_PROGRAM = [
    { type: 'set', register: 'a', value: 1 },
    { type: 'add', register: 'a', value: 2 },
    { type: 'mul', register: 'a', value: 'a' },
    { type: 'mod', register: 'a', value: 5 },
    { type: 'snd', register: 'a' },
    { type: 'set', register: 'a', value: 0 },
    { type: 'rcv', value: 'a' },
    { type: 'jgz', value: 'a', offset: -1 },
    { type: 'set', register: 'a', value: 1 },
    { type: 'jgz', value: 'a', offset: -2 },
];
