const PROGRAM = [
    { type: 'set', x: 'i', y: 31 },
    { type: 'set', x: 'a', y: 1 },
    { type: 'mul', x: 'p', y: 17 },
    { type: 'jgz', x: 'p', y: 'p' },
    { type: 'mul', x: 'a', y: 2 },
    { type: 'add', x: 'i', y: -1 },
    { type: 'jgz', x: 'i', y: -2 },
    { type: 'add', x: 'a', y: -1 },
    { type: 'set', x: 'i', y: 127 },
    { type: 'set', x: 'p', y: 464 },
    { type: 'mul', x: 'p', y: 8505 },
    { type: 'mod', x: 'p', y: 'a' },
    { type: 'mul', x: 'p', y: 129749 },
    { type: 'add', x: 'p', y: 12345 },
    { type: 'mod', x: 'p', y: 'a' },
    { type: 'set', x: 'b', y: 'p' },
    { type: 'mod', x: 'b', y: 10000 },
    { type: 'snd', x: 'b' },
    { type: 'add', x: 'i', y: -1 },
    { type: 'jgz', x: 'i', y: -9 },
    { type: 'jgz', x: 'a', y: 3 },
    { type: 'rcv', x: 'b' },
    { type: 'jgz', x: 'b', y: -1 },
    { type: 'set', x: 'f', y: 0 },
    { type: 'set', x: 'i', y: 126 },
    { type: 'rcv', x: 'a' },
    { type: 'rcv', x: 'b' },
    { type: 'set', x: 'p', y: 'a' },
    { type: 'mul', x: 'p', y: -1 },
    { type: 'add', x: 'p', y: 'b' },
    { type: 'jgz', x: 'p', y: 4 },
    { type: 'snd', x: 'a' },
    { type: 'set', x: 'a', y: 'b' },
    { type: 'jgz', x: 1, y: 3 },
    { type: 'snd', x: 'b' },
    { type: 'set', x: 'f', y: 1 },
    { type: 'add', x: 'i', y: -1 },
    { type: 'jgz', x: 'i', y: -11 },
    { type: 'snd', x: 'a' },
    { type: 'jgz', x: 'f', y: -16 },
    { type: 'jgz', x: 'a', y: -19 },
];

const SAMPLE_PROGRAM = [
    { type: 'set', x: 'a', y: 1 },
    { type: 'add', x: 'a', y: 2 },
    { type: 'mul', x: 'a', y: 'a' },
    { type: 'mod', x: 'a', y: 5 },
    { type: 'snd', x: 'a' },
    { type: 'set', x: 'a', y: 0 },
    { type: 'rcv', x: 'a' },
    { type: 'jgz', x: 'a', y: -1 },
    { type: 'set', x: 'a', y: 1 },
    { type: 'jgz', x: 'a', y: -2 },
];

module.exports = {
    input: PROGRAM,
    sampleInput: SAMPLE_PROGRAM,
};
