const PROGRAM = [
    { type: 'set', x: 'b', y: 67 },
    { type: 'set', x: 'c', y: 'b' },
    { type: 'jnz', x: 'a', y: 2 },
    { type: 'jnz', x: 1, y: 5 },
    { type: 'mul', x: 'b', y: 100 },
    { type: 'sub', x: 'b', y: -100000 },
    { type: 'set', x: 'c', y: 'b' },
    { type: 'sub', x: 'c', y: -17000 },
    { type: 'set', x: 'f', y: 1 },
    { type: 'set', x: 'd', y: 2 },
    { type: 'set', x: 'e', y: 2 },
    { type: 'set', x: 'g', y: 'd' },
    { type: 'mul', x: 'g', y: 'e' },
    { type: 'sub', x: 'g', y: 'b' },
    { type: 'jnz', x: 'g', y: 2 },
    { type: 'set', x: 'f', y: 0 },
    { type: 'sub', x: 'e', y: -1 },
    { type: 'set', x: 'g', y: 'e' },
    { type: 'sub', x: 'g', y: 'b' },
    { type: 'jnz', x: 'g', y: -8 },
    { type: 'sub', x: 'd', y: -1 },
    { type: 'set', x: 'g', y: 'd' },
    { type: 'sub', x: 'g', y: 'b' },
    { type: 'jnz', x: 'g', y: -13 },
    { type: 'jnz', x: 'f', y: 2 },
    { type: 'sub', x: 'h', y: -1 },
    { type: 'set', x: 'g', y: 'b' },
    { type: 'sub', x: 'g', y: 'c' },
    { type: 'jnz', x: 'g', y: 2 },
    { type: 'jnz', x: 1, y: 3 },
    { type: 'sub', x: 'b', y: -17 },
    { type: 'jnz', x: 1, y: -23 },
];

module.exports = {
    input: PROGRAM,
};
