const plain_rules = [
    ['Al', 'ThF'],
    ['Al', 'ThRnFAr'],
    ['B', 'BCa'],
    ['B', 'TiB'],
    ['B', 'TiRnFAr'],
    ['Ca', 'CaCa'],
    ['Ca', 'PB'],
    ['Ca', 'PRnFAr'],
    ['Ca', 'SiRnFYFAr'],
    ['Ca', 'SiRnMgAr'],
    ['Ca', 'SiTh'],
    ['F', 'CaF'],
    ['F', 'PMg'],
    ['F', 'SiAl'],
    ['H', 'CRnAlAr'],
    ['H', 'CRnFYFYFAr'],
    ['H', 'CRnFYMgAr'],
    ['H', 'CRnMgYFAr'],
    ['H', 'HCa'],
    ['H', 'NRnFYFAr'],
    ['H', 'NRnMgAr'],
    ['H', 'NTh'],
    ['H', 'OB'],
    ['H', 'ORnFAr'],
    ['Mg', 'BF'],
    ['Mg', 'TiMg'],
    ['N', 'CRnFAr'],
    ['N', 'HSi'],
    ['O', 'CRnFYFAr'],
    ['O', 'CRnMgAr'],
    ['O', 'HP'],
    ['O', 'NRnFAr'],
    ['O', 'OTi'],
    ['P', 'CaP'],
    ['P', 'PTi'],
    ['P', 'SiRnFAr'],
    ['Si', 'CaSi'],
    ['Th', 'ThCa'],
    ['Ti', 'BP'],
    ['Ti', 'TiTi'],
    ['e', 'HF'],
    ['e', 'NAl'],
    ['e', 'OMg'],
];

const isUpperCase = /[A-Z]/;
const splitMolecule = (molecule) => {
    let mol_arr = [];
    let acc = molecule[0];
    for (let i = 1; i < molecule.length; i++) {
        let char = molecule[i];
        if (isUpperCase.test(char)) {
            mol_arr.push(acc);
            acc = '';
        }

        acc += char;
    }

    if (acc) {
        mol_arr.push(acc);
    }

    return mol_arr;
}

// Create rules map
let rules = {};
plain_rules.forEach(([start, end]) => {
    if (!rules[start]) {
        rules[start] = [];
    }

    rules[start].push(end);
});

module.exports = {
    splitMolecule,
    sampleInput: {
        rules: {
            e: ['H', 'O'],
            H: ['HO', 'OH'],
            O: ['HH'],
        },
        initialState: ['H', 'O', 'H'],
    },

    input: {
        rules: rules,

        initialState: [
            'C',
            'Rn',
            'Si',
            'Rn',
            'Ca',
            'P',
            'Ti',
            'Mg',
            'Y',
            'Ca',
            'P',
            'Ti',
            'Rn',
            'F',
            'Ar',
            'Si',
            'Th',
            'F',
            'Ar',
            'Ca',
            'Si',
            'Th',
            'Si',
            'Th',
            'P',
            'B',
            'Ca',
            'Ca',
            'Si',
            'Rn',
            'Si',
            'Rn',
            'Ti',
            'Ti',
            'Mg',
            'Ar',
            'P',
            'B',
            'Ca',
            'P',
            'Mg',
            'Y',
            'P',
            'Ti',
            'Rn',
            'F',
            'Ar',
            'F',
            'Ar',
            'Ca',
            'Si',
            'Rn',
            'B',
            'P',
            'Mg',
            'Ar',
            'P',
            'Rn',
            'Ca',
            'P',
            'Ti',
            'Rn',
            'F',
            'Ar',
            'Ca',
            'Si',
            'Th',
            'Ca',
            'Ca',
            'F',
            'Ar',
            'P',
            'B',
            'Ca',
            'Ca',
            'P',
            'Ti',
            'Ti',
            'Rn',
            'F',
            'Ar',
            'Ca',
            'Si',
            'Rn',
            'Si',
            'Al',
            'Y',
            'Si',
            'Th',
            'Rn',
            'F',
            'Ar',
            'Ar',
            'Ca',
            'Si',
            'Rn',
            'B',
            'F',
            'Ar',
            'Ca',
            'Ca',
            'Si',
            'Rn',
            'Si',
            'Th',
            'Ca',
            'Ca',
            'Ca',
            'F',
            'Y',
            'Ca',
            'P',
            'Ti',
            'B',
            'Ca',
            'Si',
            'Th',
            'Ca',
            'Si',
            'Th',
            'P',
            'Mg',
            'Ar',
            'Si',
            'Rn',
            'Ca',
            'P',
            'B',
            'F',
            'Y',
            'Ca',
            'Ca',
            'F',
            'Ar',
            'Ca',
            'Ca',
            'Ca',
            'Ca',
            'Si',
            'Th',
            'Ca',
            'Si',
            'Rn',
            'P',
            'Rn',
            'F',
            'Ar',
            'P',
            'B',
            'Si',
            'Th',
            'P',
            'Rn',
            'F',
            'Ar',
            'Si',
            'Rn',
            'Mg',
            'Ar',
            'Ca',
            'F',
            'Y',
            'F',
            'Ar',
            'Ca',
            'Si',
            'Rn',
            'Si',
            'Al',
            'Ar',
            'Ti',
            'Ti',
            'Ti',
            'Ti',
            'Ti',
            'Ti',
            'Ti',
            'Rn',
            'P',
            'Mg',
            'Ar',
            'P',
            'Ti',
            'Ti',
            'Ti',
            'B',
            'Si',
            'Rn',
            'Si',
            'Al',
            'Ar',
            'Ti',
            'Ti',
            'Rn',
            'P',
            'Mg',
            'Ar',
            'Ca',
            'F',
            'Y',
            'B',
            'P',
            'B',
            'P',
            'Ti',
            'Rn',
            'Si',
            'Rn',
            'Mg',
            'Ar',
            'Si',
            'Th',
            'Ca',
            'F',
            'Ar',
            'Ca',
            'Si',
            'Th',
            'F',
            'Ar',
            'P',
            'Rn',
            'F',
            'Ar',
            'Ca',
            'Si',
            'Rn',
            'Ti',
            'B',
            'Si',
            'Th',
            'Si',
            'Rn',
            'Si',
            'Al',
            'Y',
            'Ca',
            'F',
            'Ar',
            'P',
            'Rn',
            'F',
            'Ar',
            'Si',
            'Th',
            'Ca',
            'F',
            'Ar',
            'Ca',
            'Ca',
            'Si',
            'Th',
            'Ca',
            'Ca',
            'Ca',
            'Si',
            'Rn',
            'P',
            'Rn',
            'Ca',
            'F',
            'Ar',
            'F',
            'Y',
            'P',
            'Mg',
            'Ar',
            'Ca',
            'P',
            'B',
            'Ca',
            'P',
            'B',
            'Si',
            'Rn',
            'F',
            'Y',
            'P',
            'B',
            'Ca',
            'F',
            'Ar',
            'Ca',
            'Si',
            'Al',
        ],
    },
};
