const DATA = [
    { id: 'fjkfpm', weight: 69, children: ['kohxzh', 'liwvq', 'eqkio', 'xvoyybs'] },
    { id: 'dsiixv', weight: 52, children: [] },
    { id: 'fhimhm', weight: 66, children: [] },
    { id: 'mdlubuq', weight: 73, children: [] },
    { id: 'ulobwyb', weight: 41, children: [] },
    { id: 'cbgnzhz', weight: 70, children: [] },
    { id: 'hrheyzf', weight: 946, children: ['fixqj', 'msyvs', 'pdwjcd', 'tlgdija'] },
    { id: 'yrnjhqc', weight: 31, children: [] },
    { id: 'xlglga', weight: 714, children: ['hohft', 'funabvw', 'zhxnpoh', 'unpdcwm'] },
    { id: 'hcvwov', weight: 240, children: [] },
    { id: 'qnhvjec', weight: 35016, children: ['pimzjjp', 'ghatw', 'tbakk', 'olgmto', 'qeaqiuq', 'wnmnz', 'aabbf'] },
    { id: 'efgdfa', weight: 405, children: ['uyedi', 'rxkmf', 'syhipz', 'zozcoqd', 'uwprsvh', 'dqhoh', 'rcbhgw'] },
    { id: 'vofrtf', weight: 55, children: [] },
    { id: 'gipbso', weight: 52, children: [] },
    { id: 'cviwy', weight: 426, children: ['ildgly', 'syojg', 'tgoztyw', 'doavm'] },
    { id: 'okzkfw', weight: 159, children: ['ndteuz', 'bkmepbs'] },
    { id: 'ylfvgv', weight: 5, children: [] },
    { id: 'ydxuhqe', weight: 72, children: ['bfftnj', 'uwrll', 'njlaepf', 'kbfpx'] },
    { id: 'hwfcy', weight: 54, children: [] },
    { id: 'iqtdzrh', weight: 65, children: ['qoppte', 'jcsqqxv'] },
    { id: 'ddumyx', weight: 220, children: ['yjowio', 'gefjk'] },
    { id: 'edagh', weight: 12, children: [] },
    { id: 'kefudoj', weight: 82, children: [] },
    { id: 'indjoox', weight: 36, children: [] },
    { id: 'cliojs', weight: 35, children: [] },
    { id: 'lrvmyj', weight: 79, children: ['fadkfic', 'pcikcq', 'fgeup'] },
    { id: 'mvyzuw', weight: 73, children: [] },
    { id: 'nholw', weight: 52, children: [] },
    { id: 'sjbqzk', weight: 212, children: ['sijon', 'bcedyx'] },
    { id: 'majskr', weight: 49, children: [] },
    { id: 'qjutng', weight: 15, children: [] },
    { id: 'iavwfbb', weight: 19, children: [] },
    { id: 'ywonug', weight: 50, children: ['dgjyf', 'kobwktw'] },
    { id: 'taxky', weight: 77, children: [] },
    { id: 'lufkiy', weight: 44, children: [] },
    { id: 'lcwqdxx', weight: 34, children: [] },
    { id: 'felksho', weight: 204, children: ['vkile', 'ihadu', 'qfczh', 'wvgzlw', 'axawjtm', 'eutun', 'vkzmf'] },
    { id: 'rvtus', weight: 94, children: [] },
    { id: 'zjxjhwc', weight: 53, children: [] },
    { id: 'bnmsz', weight: 95, children: [] },
    { id: 'cvcyykp', weight: 31, children: [] },
    { id: 'bfxvxpl', weight: 35, children: [] },
    { id: 'niavkxg', weight: 16, children: [] },
    { id: 'zwcsjgs', weight: 7, children: [] },
    { id: 'gtqwrrx', weight: 44, children: [] },
    { id: 'vszpkfs', weight: 107, children: ['rubvop', 'qsvjd'] },
    { id: 'axawjtm', weight: 12, children: ['gtbocpw', 'oxlvr', 'mvfjras', 'vgyzdkt'] },
    { id: 'ulvbf', weight: 82, children: [] },
    { id: 'vkzmf', weight: 252, children: [] },
    { id: 'jnedlwi', weight: 100, children: ['rkftwvy', 'gwyrtw'] },
    { id: 'sztry', weight: 247, children: ['vddarvs', 'tlzlq'] },
    { id: 'anwbrxk', weight: 69, children: ['ybnsg', 'rfwgt', 'pcppql'] },
    { id: 'pfxoef', weight: 66, children: [] },
    { id: 'ghqixh', weight: 171, children: ['cjcytbb', 'dmare'] },
    { id: 'jwrmi', weight: 130, children: ['mhrzazo', 'qeuwgn'] },
    { id: 'umsrz', weight: 7, children: ['jwrbg', 'wqpahuv', 'zquvn', 'sfjyf', 'uebmnqa', 'qqkqhzb', 'gmbup'] },
    { id: 'wtsqx', weight: 46, children: [] },
    { id: 'rzldn', weight: 31, children: [] },
    { id: 'usmtdk', weight: 166, children: ['pikelbw', 'edwlns'] },
    { id: 'pyhecs', weight: 59, children: [] },
    { id: 'shwsf', weight: 56, children: ['wtbst', 'ryjqaz'] },
    { id: 'jhkkrg', weight: 63, children: [] },
    { id: 'eaagt', weight: 40, children: [] },
    { id: 'wkbqm', weight: 59, children: [] },
    { id: 'iivwxhd', weight: 150, children: ['yfgyi', 'grdimrp'] },
    { id: 'nlkwsrn', weight: 50, children: [] },
    { id: 'idnsypp', weight: 94, children: [] },
    { id: 'aixwgk', weight: 41, children: [] },
    { id: 'yhhnavm', weight: 84, children: [] },
    { id: 'lngdxkd', weight: 146, children: ['hkkzpzh', 'ihvfxeo'] },
    { id: 'dkwwoa', weight: 73, children: ['sntbr', 'xbywgft', 'xlkvx', 'akght'] },
    { id: 'jevqne', weight: 8, children: [] },
    { id: 'vurnn', weight: 81, children: ['fkehyrg', 'qhktzou'] },
    { id: 'ngoog', weight: 20, children: ['uusec', 'rrnkqx', 'jafsqqu', 'ryeiot'] },
    { id: 'hxhguzh', weight: 75, children: [] },
    { id: 'kohxzh', weight: 1765, children: ['mjpmw', 'cbmkr', 'vmofl', 'wsjizsy', 'redeub'] },
    { id: 'twpvnu', weight: 56, children: [] },
    { id: 'kzumm', weight: 132, children: ['czgxag', 'vytlfm', 'qowepn'] },
    { id: 'fgnye', weight: 44, children: ['pxcjw', 'bnmuprs'] },
    { id: 'jvqfj', weight: 60, children: [] },
    { id: 'yvllxxw', weight: 55, children: [] },
    { id: 'hsmaze', weight: 34, children: ['fxzqvoh', 'fcvsqp', 'okzkfw', 'vwtsdsf', 'ipbbnp', 'txdprek'] },
    { id: 'aujdy', weight: 14, children: [] },
    { id: 'yjcevge', weight: 61, children: ['rpyxxhm', 'tfbqaoe'] },
    { id: 'blcpm', weight: 217, children: ['qibrsjj', 'wcfykko'] },
    { id: 'pfltnc', weight: 44, children: [] },
    { id: 'anqas', weight: 63, children: ['riuwg', 'jhkkrg'] },
    { id: 'rtseps', weight: 51, children: [] },
    { id: 'vmkfcpw', weight: 92, children: [] },
    { id: 'pcppql', weight: 78, children: [] },
    { id: 'tqrqs', weight: 43, children: [] },
    { id: 'syxdt', weight: 12, children: [] },
    { id: 'ejlecie', weight: 79, children: [] },
    { id: 'xpdmegi', weight: 16, children: [] },
    { id: 'dgjyf', weight: 62, children: [] },
    { id: 'uxhpm', weight: 51, children: [] },
    { id: 'znchnta', weight: 66, children: ['sutzt', 'kvjyw', 'hlshpkq', 'corcne', 'rflrj', 'yhadh', 'ouypz'] },
    { id: 'zmdvl', weight: 50, children: [] },
    { id: 'fixysjm', weight: 1386, children: ['zjylql', 'ytadaxm', 'fgnye'] },
    { id: 'yevywe', weight: 63, children: ['qeayjnt', 'ixyeq', 'hgaoiz', 'rcfaaml', 'zuzhmf'] },
    { id: 'rxkmf', weight: 811, children: ['yedvssr', 'xvwgxm', 'wfeurd'] },
    { id: 'mcmzs', weight: 53, children: [] },
    { id: 'vsmdkp', weight: 60, children: [] },
    { id: 'oyurf', weight: 27, children: ['zhjtcdl', 'jswxshd', 'hfwpcsa', 'lbvfwz', 'obolmhh', 'grgkv'] },
    { id: 'yawmlbb', weight: 191, children: ['iavwfbb', 'xjjvneg'] },
    { id: 'fblsn', weight: 44, children: [] },
    { id: 'doavm', weight: 223, children: ['drasjw', 'cwwwcge'] },
    { id: 'udyivld', weight: 18, children: ['osrdt', 'jpyojky', 'vhnnnv', 'gyxqc'] },
    { id: 'ddqnllo', weight: 167, children: ['cdfij', 'quohxia'] },
    { id: 'bwbym', weight: 55, children: [] },
    { id: 'ufpdyq', weight: 22, children: [] },
    { id: 'hkjcnv', weight: 73, children: ['nderndc', 'owjtoo'] },
    { id: 'ndhravs', weight: 10, children: [] },
    { id: 'qjkkohe', weight: 25, children: [] },
    { id: 'jrott', weight: 44, children: ['jgylf', 'kaitdu'] },
    { id: 'unvqq', weight: 173, children: ['lxdji', 'ldkojcj'] },
    { id: 'zrgqfb', weight: 81, children: [] },
    { id: 'csbgxs', weight: 29, children: [] },
    { id: 'qeaqiuq', weight: 1106, children: ['nwlkk', 'ytyhmux', 'nxmtm', 'izpta'] },
    { id: 'rqeftjw', weight: 51, children: [] },
    { id: 'tbakbq', weight: 62, children: [] },
    { id: 'vnhhu', weight: 62, children: [] },
    { id: 'grgkv', weight: 85, children: ['xgmrufk', 'cvvkno'] },
    { id: 'pggrr', weight: 29, children: ['bttvl', 'zrmzpo', 'upatvy'] },
    { id: 'zumdwwu', weight: 43, children: ['jfssr', 'aujdy', 'adkyx', 'mragx'] },
    { id: 'euxvn', weight: 105, children: ['qtazfdw', 'uzarat', 'mikalda'] },
    { id: 'tpbcg', weight: 98, children: [] },
    { id: 'kdnwlnz', weight: 36, children: [] },
    { id: 'pncda', weight: 183, children: ['uswszht', 'zeebqts'] },
    { id: 'zlvjnx', weight: 130, children: ['vctupmx', 'gmxdpc'] },
    { id: 'iljdm', weight: 203, children: ['emqwt', 'leknm'] },
    { id: 'lmgxknk', weight: 49, children: [] },
    { id: 'pikelbw', weight: 34, children: [] },
    { id: 'kqqegw', weight: 89, children: [] },
    { id: 'eigsdc', weight: 20, children: [] },
    { id: 'qbhvu', weight: 94, children: [] },
    { id: 'kqoae', weight: 61, children: ['tqrqs', 'bfozr', 'kkqeg'] },
    { id: 'bozfw', weight: 5, children: [] },
    { id: 'silwwua', weight: 20867, children: ['kzocw', 'ymhsa', 'mzcebu'] },
    { id: 'fcxninx', weight: 473, children: ['pmxzfd', 'kbvzpv', 'zskam', 'oyurf'] },
    { id: 'ihvfxeo', weight: 14, children: [] },
    { id: 'rkftwvy', weight: 52, children: [] },
    { id: 'kccra', weight: 26, children: [] },
    { id: 'vkxbeox', weight: 353, children: [] },
    { id: 'suiagk', weight: 59, children: [] },
    { id: 'lnqzgti', weight: 60, children: [] },
    { id: 'leknm', weight: 50, children: [] },
    { id: 'yxvmxzg', weight: 35, children: [] },
    { id: 'jezubi', weight: 54, children: ['lnqzgti', 'hvsiuf'] },
    { id: 'bzqhk', weight: 33, children: ['ndmpgss', 'kcoayj'] },
    { id: 'xaovjvs', weight: 74, children: [] },
    { id: 'mjuyo', weight: 263, children: ['psrup', 'boeuyxx'] },
    { id: 'tvoptyn', weight: 1776, children: ['xjbtfms', 'tiphry'] },
    { id: 'jbhohbx', weight: 25, children: [] },
    { id: 'kqfgnql', weight: 22, children: ['pmozz', 'hspqr', 'ydxuhqe', 'txhxoib', 'cncoep', 'ripidvx', 'qezvrjl'] },
    { id: 'pdkfixk', weight: 22, children: [] },
    { id: 'kxzwel', weight: 80, children: [] },
    { id: 'sykmuwo', weight: 243, children: ['zvogn', 'esmbu'] },
    { id: 'livul', weight: 40, children: [] },
    { id: 'rvmntl', weight: 346, children: [] },
    { id: 'xqztuq', weight: 24, children: ['pyhecs', 'jqgkz', 'bsythck', 'ranlxct'] },
    { id: 'edyohkw', weight: 79, children: [] },
    { id: 'hszzxp', weight: 64, children: ['xcdswr', 'oukuy'] },
    { id: 'yfgyi', weight: 56, children: [] },
    { id: 'pmozz', weight: 74, children: ['ngaawt', 'oaknu', 'cgbkrnc'] },
    { id: 'tfglbeh', weight: 56, children: [] },
    { id: 'wpvozgo', weight: 53, children: [] },
    { id: 'njaig', weight: 77, children: [] },
    { id: 'jwrbg', weight: 134, children: ['fymyi', 'utpyp', 'ulxscm', 'cliojs'] },
    { id: 'olnfe', weight: 33, children: [] },
    { id: 'jcsqqxv', weight: 52, children: [] },
    { id: 'fvkew', weight: 21, children: [] },
    { id: 'nkdbmjv', weight: 34, children: [] },
    { id: 'fhjgv', weight: 55, children: [] },
    { id: 'tvqlaw', weight: 14, children: [] },
    { id: 'wqpahuv', weight: 274, children: [] },
    { id: 'myoyl', weight: 82, children: [] },
    { id: 'pjzcs', weight: 38, children: [] },
    { id: 'pcehxbx', weight: 1859, children: ['hlfmvdt', 'ngoog', 'mwhraq'] },
    { id: 'kqohkg', weight: 56, children: ['hezkdc', 'kgfudu', 'omeew'] },
    { id: 'adtpk', weight: 1655, children: ['unvqq', 'bpbwl', 'anqas', 'kmnzz'] },
    { id: 'afihdk', weight: 65, children: [] },
    { id: 'rtiaapt', weight: 18, children: [] },
    { id: 'obolmhh', weight: 109, children: ['lufkiy', 'kiryhz'] },
    { id: 'dkegbrt', weight: 45, children: [] },
    { id: 'rbiarxk', weight: 81, children: ['erngeah', 'cqcjys', 'bxjqibv'] },
    { id: 'hmrzqlh', weight: 87, children: [] },
    { id: 'biemun', weight: 295, children: ['ejbtu', 'hszzxp', 'kcxiq', 'khixwdd', 'usmtdk'] },
    { id: 'mvfjras', weight: 60, children: [] },
    { id: 'uqktn', weight: 246, children: ['gtqwrrx', 'qtshuo'] },
    { id: 'kmpmdb', weight: 8, children: [] },
    { id: 'lylxk', weight: 22, children: [] },
    { id: 'nxmtm', weight: 84, children: [] },
    { id: 'goapac', weight: 88, children: [] },
    { id: 'zlxlwv', weight: 43, children: [] },
    { id: 'nirov', weight: 74, children: [] },
    { id: 'fcjjqev', weight: 78, children: [] },
    { id: 'finxtiu', weight: 92, children: ['vgdsszs', 'gofjvi', 'mxpvph'] },
    { id: 'uvpwrf', weight: 73, children: [] },
    { id: 'vgnkq', weight: 104, children: ['jczkx', 'iydqii'] },
    { id: 'gsbmh', weight: 84, children: [] },
    { id: 'ssblis', weight: 86, children: [] },
    { id: 'knvxq', weight: 1845, children: ['pvbgvb', 'mcghosj', 'qocnylk'] },
    { id: 'kvjyw', weight: 57, children: ['livul', 'eaagt', 'rukzsa', 'gsdzpjh'] },
    { id: 'zhpdhat', weight: 76, children: [] },
    { id: 'ypjnmr', weight: 39, children: [] },
    { id: 'yauryvu', weight: 97, children: [] },
    { id: 'ucahbv', weight: 82, children: [] },
    { id: 'rkswk', weight: 70, children: ['kccra', 'lqasevp', 'bdvtnul', 'swqres'] },
    { id: 'bqvtbsr', weight: 39, children: [] },
    { id: 'cmfcqh', weight: 149, children: ['wlwnand', 'zikmmr'] },
    { id: 'ouypz', weight: 67, children: ['mxelfv', 'fogmaih'] },
    { id: 'nlrbcxx', weight: 41, children: [] },
    { id: 'mrmuat', weight: 21, children: [] },
    { id: 'kcxiq', weight: 150, children: ['mdvnu', 'dcwcs'] },
    { id: 'aabbf', weight: 881, children: ['dsoyvp', 'hwraaxu', 'lrvmyj'] },
    { id: 'mjxfsc', weight: 53, children: [] },
    { id: 'dmare', weight: 55, children: [] },
    { id: 'iruee', weight: 89, children: [] },
    { id: 'gpsnzs', weight: 76, children: [] },
    { id: 'wnpkwy', weight: 27, children: [] },
    { id: 'zvnzep', weight: 174, children: ['tvqlaw', 'aufxtq'] },
    { id: 'yysyjbk', weight: 1630, children: ['wpvozgo', 'mjxfsc', 'iality', 'vwupkmh'] },
    { id: 'cgbkrnc', weight: 62, children: [] },
    { id: 'mnfknb', weight: 41, children: [] },
    { id: 'kcoayj', weight: 89, children: [] },
    { id: 'vybmch', weight: 79, children: ['ebyfpmf', 'dnqdmxc'] },
    { id: 'lmrzi', weight: 87, children: [] },
    { id: 'tiyvea', weight: 30, children: [] },
    { id: 'pcikcq', weight: 36, children: [] },
    { id: 'mlqoz', weight: 20, children: [] },
    { id: 'brmvw', weight: 144, children: ['qjutng', 'janbnmh'] },
    { id: 'zgkxkj', weight: 72, children: ['bwrpc', 'wntfmtn', 'hwjmzs', 'vkxbeox'] },
    { id: 'gzcbv', weight: 54, children: [] },
    { id: 'nsqpaq', weight: 55, children: [] },
    { id: 'hohft', weight: 69, children: ['hfjtksr', 'efzjseb', 'ypjnmr', 'bqvtbsr'] },
    { id: 'kkqeg', weight: 43, children: [] },
    { id: 'gafjq', weight: 74, children: [] },
    { id: 'haano', weight: 296, children: ['rlburl', 'njkvleo'] },
    { id: 'tvbmh', weight: 99, children: [] },
    { id: 'fvsitx', weight: 212, children: ['nsvwcl', 'hohrape'] },
    { id: 'yhtpdwu', weight: 71, children: [] },
    { id: 'qxsjs', weight: 95, children: [] },
    { id: 'qseqsgt', weight: 22, children: [] },
    { id: 'vkhdfmv', weight: 36, children: [] },
    { id: 'ikicwez', weight: 69, children: [] },
    { id: 'tdrdq', weight: 24, children: [] },
    { id: 'bgudw', weight: 94, children: [] },
    { id: 'zhjtcdl', weight: 134, children: ['ceutto', 'fhynmi', 'qmyohe'] },
    { id: 'pavtnxe', weight: 38, children: [] },
    { id: 'xvoehjz', weight: 301, children: ['zznjih', 'wseim'] },
    { id: 'klfyu', weight: 40, children: [] },
    { id: 'zhxnpoh', weight: 119, children: ['ltyxiwk', 'wkgouh'] },
    { id: 'bezoxx', weight: 184, children: ['afihdk', 'jevfpj'] },
    { id: 'ivldghm', weight: 64, children: ['enmxpmj', 'wsrrryh'] },
    { id: 'osnpbou', weight: 111, children: ['zpuktmx', 'itlno'] },
    { id: 'uofuvf', weight: 70, children: [] },
    { id: 'mgvcyl', weight: 51, children: ['nsqpaq', 'fhjgv'] },
    { id: 'lluabej', weight: 97, children: [] },
    { id: 'hwjmzs', weight: 273, children: ['agsfbkx', 'znswber'] },
    { id: 'udlhalx', weight: 26, children: [] },
    { id: 'gewlsr', weight: 476, children: ['uqktn', 'nknpwkc', 'udyivld'] },
    { id: 'fsjvyxv', weight: 27, children: [] },
    { id: 'birtjxh', weight: 78, children: [] },
    { id: 'eplltu', weight: 84, children: [] },
    { id: 'sdixs', weight: 54, children: [] },
    { id: 'kqdseyh', weight: 46, children: [] },
    { id: 'lfrfa', weight: 76, children: ['ejlecie', 'mvxud', 'wgevvca', 'carfsnj'] },
    { id: 'lbwgsap', weight: 33, children: ['gpsnzs', 'santsu'] },
    { id: 'pnjtt', weight: 45, children: [] },
    { id: 'rcfaaml', weight: 157, children: ['avemxf', 'ehwcxy'] },
    { id: 'tbutks', weight: 36, children: [] },
    { id: 'xmhdsio', weight: 91, children: [] },
    { id: 'byjcsn', weight: 51, children: [] },
    { id: 'amslmyk', weight: 96, children: [] },
    { id: 'jtdvzj', weight: 62, children: [] },
    { id: 'xnaam', weight: 88, children: ['lylxk', 'sybcl', 'kuqsuy'] },
    { id: 'boeuyxx', weight: 53, children: [] },
    { id: 'pxcwhq', weight: 30, children: [] },
    { id: 'mckyvtt', weight: 52, children: [] },
    { id: 'pctkyat', weight: 25, children: [] },
    { id: 'lomxh', weight: 53, children: [] },
    { id: 'ltccbob', weight: 297, children: ['ndhravs', 'qlryl'] },
    { id: 'vgyzdkt', weight: 60, children: [] },
    { id: 'pyzbqz', weight: 74, children: [] },
    { id: 'cjkieim', weight: 519, children: ['myeecwt', 'agtab', 'rhtqj', 'mmriyf', 'mfcutqz'] },
    { id: 'ducdc', weight: 41, children: [] },
    { id: 'mnxoac', weight: 30, children: [] },
    { id: 'umtmwow', weight: 30, children: [] },
    { id: 'qsxqwub', weight: 94, children: ['klfyu', 'mlzfw'] },
    { id: 'pdwjcd', weight: 105, children: ['vcoszdq', 'fkmpv'] },
    { id: 'wifaf', weight: 41, children: ['dnunil', 'gafjq', 'gwgchq'] },
    { id: 'tpabsyz', weight: 91, children: [] },
    { id: 'uwrll', weight: 47, children: [] },
    { id: 'dcjiqny', weight: 1371, children: ['npblyaq', 'qeoetnp', 'qoeviy'] },
    { id: 'rlburl', weight: 9, children: [] },
    { id: 'itlno', weight: 37, children: [] },
    { id: 'ehpdfno', weight: 285, children: ['bcrso', 'jqwaifx'] },
    { id: 'njkvleo', weight: 9, children: [] },
    { id: 'uswszht', weight: 24, children: [] },
    { id: 'qvpou', weight: 180, children: ['sndject', 'bzmhwwo'] },
    { id: 'ngaawt', weight: 62, children: [] },
    { id: 'kyhezqn', weight: 45, children: [] },
    { id: 'arouwsi', weight: 59, children: [] },
    { id: 'uyoez', weight: 99, children: [] },
    { id: 'quoqibc', weight: 195, children: ['znuldtj', 'bljppq'] },
    { id: 'tiphry', weight: 33, children: [] },
    { id: 'lbvfwz', weight: 89, children: ['qypsl', 'gzcbv'] },
    { id: 'bzmhwwo', weight: 5, children: [] },
    { id: 'tcbxnrf', weight: 285, children: ['ybgdelp', 'aqrpio'] },
    { id: 'arjgn', weight: 392, children: [] },
    { id: 'qfczh', weight: 218, children: ['ivhtlxa', 'jdazgj'] },
    { id: 'jpyojky', weight: 79, children: [] },
    { id: 'zinjsj', weight: 30, children: [] },
    { id: 'qfsmgqe', weight: 982, children: ['mgvcyl', 'cekchxh', 'qnscg'] },
    { id: 'mlzfw', weight: 40, children: [] },
    { id: 'ulszlax', weight: 42, children: [] },
    { id: 'myeecwt', weight: 69, children: ['veiljb', 'wydtqax', 'pnjtt', 'sxwbzyj'] },
    { id: 'vkuucpv', weight: 260, children: ['fenymdp', 'uwehdau'] },
    { id: 'qezvrjl', weight: 212, children: ['jdqhjk', 'htwzu', 'lzevbng'] },
    { id: 'qnscg', weight: 161, children: [] },
    { id: 'wkkkv', weight: 11, children: [] },
    { id: 'bpbwl', weight: 149, children: ['mlqoz', 'miwjfr'] },
    { id: 'icspwbg', weight: 83, children: ['iljdm', 'sztry', 'anwbrxk', 'ddqnllo', 'gtbmrcp', 'cpzwgk'] },
    { id: 'bddlvs', weight: 70, children: [] },
    { id: 'mragx', weight: 14, children: [] },
    { id: 'vdyhna', weight: 166, children: ['glori', 'azttml', 'jxraf'] },
    { id: 'zjylql', weight: 78, children: ['fsoqc', 'hefjuue'] },
    { id: 'jdqhjk', weight: 16, children: [] },
    { id: 'etkzf', weight: 11, children: [] },
    { id: 'grdimrp', weight: 56, children: [] },
    { id: 'tlics', weight: 101, children: ['twpvnu', 'tfglbeh'] },
    { id: 'kskkjn', weight: 1081, children: ['uxmjgh', 'kqoae', 'wswwck', 'zwymlsj', 'qvpou', 'mtxzek', 'elxccty'] },
    { id: 'qsvjd', weight: 31, children: [] },
    { id: 'uurqa', weight: 33, children: [] },
    { id: 'gytzi', weight: 18, children: [] },
    { id: 'xsvage', weight: 27, children: [] },
    { id: 'gefjk', weight: 21, children: [] },
    { id: 'vpbec', weight: 263, children: [] },
    { id: 'mocpa', weight: 79, children: ['ldvcrw', 'atxfply', 'ogtxa', 'rbbkdj', 'blcpm'] },
    { id: 'wsdqchf', weight: 71, children: [] },
    { id: 'zznjih', weight: 11, children: [] },
    { id: 'ryjqaz', weight: 73, children: [] },
    { id: 'hspqr', weight: 66, children: ['hjxzwnq', 'ojrixty'] },
    { id: 'phkzo', weight: 263, children: ['licst', 'nbkzscx'] },
    { id: 'haayebg', weight: 39, children: ['ogziig', 'pyscsi'] },
    { id: 'kbdnbnd', weight: 94, children: [] },
    { id: 'ioyealn', weight: 51, children: [] },
    { id: 'nuoic', weight: 20, children: ['pmssap', 'bzuago', 'tvbmh'] },
    { id: 'kuqsuy', weight: 22, children: [] },
    { id: 'hvsiuf', weight: 60, children: [] },
    { id: 'werskvv', weight: 78, children: [] },
    { id: 'hohrape', weight: 90, children: [] },
    { id: 'sybcl', weight: 22, children: [] },
    { id: 'ksnxlcl', weight: 117, children: ['sdjxpp', 'yzpyzu', 'ulobwyb', 'afbnq'] },
    { id: 'qlchz', weight: 5277, children: ['doxfeq', 'luiiv', 'hsmaze'] },
    { id: 'ihadu', weight: 144, children: ['dquqam', 'ctvrea'] },
    { id: 'dquqam', weight: 54, children: [] },
    { id: 'pjamo', weight: 113, children: ['vnhhu', 'jtdvzj'] },
    { id: 'xeypnpr', weight: 183, children: ['qiund', 'kdnwlnz'] },
    { id: 'loaft', weight: 59, children: [] },
    { id: 'loykzr', weight: 16, children: [] },
    { id: 'bsbsdiu', weight: 81, children: ['ssmhkwq', 'alolk'] },
    { id: 'efzjseb', weight: 39, children: [] },
    { id: 'lbkrk', weight: 17, children: [] },
    { id: 'ipbbnp', weight: 127, children: ['iauetan', 'tbakbq'] },
    { id: 'uilvahq', weight: 1076, children: ['oztxjfl', 'oiufrau', 'ewyrp'] },
    { id: 'gmbup', weight: 274, children: [] },
    { id: 'gldvef', weight: 18, children: [] },
    { id: 'evvfcyi', weight: 13, children: [] },
    { id: 'nbhdty', weight: 97, children: [] },
    { id: 'ncbrxsy', weight: 15, children: [] },
    { id: 'dnunil', weight: 74, children: [] },
    { id: 'zcggn', weight: 56, children: [] },
    { id: 'mbcwjt', weight: 225, children: ['wxyaqte', 'kpffozq'] },
    { id: 'vgkjgy', weight: 16, children: [] },
    { id: 'bcnqhw', weight: 298, children: ['ohqivu', 'jzwusi', 'jzcstbe', 'xayqwyj', 'kmwkft'] },
    { id: 'gyxqc', weight: 79, children: [] },
    { id: 'ripidvx', weight: 148, children: ['rergyy', 'rwhjmp'] },
    { id: 'mxpvph', weight: 67, children: [] },
    { id: 'iauetan', weight: 62, children: [] },
    { id: 'voawog', weight: 34, children: [] },
    { id: 'mzcebu', weight: 11, children: ['rlgrkq', 'xlglga', 'hrheyzf', 'gbwfjf', 'mhkrny'] },
    { id: 'sexuv', weight: 92, children: ['ednlrw', 'zcggn'] },
    { id: 'fezoyaj', weight: 78, children: [] },
    { id: 'uxmjgh', weight: 70, children: ['mnxoac', 'pxcwhq', 'ytjheqk', 'tmtfhr'] },
    { id: 'tvfptpz', weight: 73, children: [] },
    { id: 'rywggm', weight: 78, children: ['gxuovng', 'ragcph', 'epstabj'] },
    { id: 'ymhsa', weight: 7457, children: ['zzqtmxd', 'yfwwrkp', 'yahzcyp', 'hmugaom'] },
    { id: 'ygvvvq', weight: 392, children: [] },
    { id: 'izssdb', weight: 215, children: ['ycseeag', 'ytzdrvj'] },
    { id: 'bttvl', weight: 95, children: [] },
    { id: 'abjmd', weight: 30, children: [] },
    { id: 'mspxpr', weight: 1837, children: ['fvhvq', 'guvto'] },
    { id: 'enogehk', weight: 45, children: [] },
    { id: 'cqcjys', weight: 44, children: [] },
    { id: 'rfllomn', weight: 107, children: ['lqndkq', 'tzkgrjf', 'lcius', 'lhlgijf'] },
    { id: 'wvdswpz', weight: 34, children: [] },
    { id: 'ocqrpkf', weight: 46, children: [] },
    { id: 'oaknu', weight: 62, children: [] },
    { id: 'qvrtwdt', weight: 1289, children: ['jnedlwi', 'sexuv', 'vcauqo'] },
    { id: 'prnno', weight: 95, children: [] },
    { id: 'wgjst', weight: 177, children: ['bozfw', 'salxel', 'jrrhzc'] },
    { id: 'teapi', weight: 35, children: [] },
    { id: 'adkyx', weight: 14, children: [] },
    { id: 'huxtvqc', weight: 16, children: [] },
    { id: 'mznsk', weight: 11, children: [] },
    { id: 'fcvsqp', weight: 183, children: ['ebjgfh', 'bnvjfq'] },
    { id: 'iwkotv', weight: 89, children: [] },
    { id: 'mkykc', weight: 90, children: [] },
    { id: 'dlrznye', weight: 83, children: [] },
    { id: 'gtxdtf', weight: 42, children: [] },
    { id: 'ahism', weight: 144, children: ['gkitfsr', 'osbndxb', 'zielffk'] },
    { id: 'znztzxd', weight: 29183, children: ['jcsjaxj', 'hrwtz', 'fcxninx'] },
    { id: 'jsbug', weight: 85, children: [] },
    { id: 'kfkhxg', weight: 51, children: [] },
    { id: 'tcpvyfj', weight: 18, children: [] },
    { id: 'fpdoney', weight: 16, children: [] },
    { id: 'kfefhun', weight: 27, children: [] },
    { id: 'iufvcm', weight: 38, children: ['xjejd', 'goapac'] },
    { id: 'fzltz', weight: 8, children: [] },
    { id: 'rukzsa', weight: 40, children: [] },
    { id: 'doxfeq', weight: 154, children: ['kzumm', 'vurnn', 'fzbwmsz', 'bsbsdiu', 'pncda', 'rtromur'] },
    { id: 'dfrzb', weight: 53, children: [] },
    { id: 'rpbeiqg', weight: 170, children: ['qseqsgt', 'qmeawpu'] },
    { id: 'ycseeag', weight: 28, children: [] },
    { id: 'blfinsi', weight: 52, children: [] },
    { id: 'kvsprca', weight: 65, children: [] },
    { id: 'uzarat', weight: 35, children: [] },
    { id: 'zzlocxd', weight: 62, children: [] },
    { id: 'iality', weight: 53, children: [] },
    { id: 'daxbf', weight: 805, children: ['iktev', 'xqztuq', 'bsvoy'] },
    { id: 'hfjpir', weight: 19, children: [] },
    { id: 'bsiwtqq', weight: 58, children: [] },
    { id: 'qnepf', weight: 88, children: [] },
    { id: 'dasmiiw', weight: 56, children: [] },
    { id: 'wseim', weight: 11, children: [] },
    { id: 'lvgrmfu', weight: 180, children: ['ngiol', 'iwidsj'] },
    { id: 'nsoju', weight: 38, children: [] },
    { id: 'zqaxyz', weight: 59, children: [] },
    { id: 'qocnylk', weight: 41, children: [] },
    { id: 'fhynmi', weight: 21, children: [] },
    { id: 'xeege', weight: 12, children: [] },
    { id: 'mfslhp', weight: 95, children: [] },
    { id: 'alolk', weight: 75, children: [] },
    { id: 'qtazfdw', weight: 35, children: [] },
    { id: 'sijon', weight: 37, children: [] },
    { id: 'zzpevgd', weight: 17, children: ['smqtcaj', 'emxwr', 'uezxhid', 'blvyrzh', 'lvgrmfu', 'vkuucpv', 'eivaf'] },
    { id: 'glori', weight: 15, children: [] },
    { id: 'ssmhkwq', weight: 75, children: [] },
    { id: 'dmkhzgg', weight: 149, children: ['fuwekd', 'bwbym'] },
    { id: 'xqrrpu', weight: 29, children: [] },
    { id: 'yjowio', weight: 21, children: [] },
    { id: 'mhrzazo', weight: 36, children: [] },
    { id: 'jakmbx', weight: 39, children: ['egyfwny', 'khdzsr'] },
    { id: 'qzgdlb', weight: 33, children: [] },
    { id: 'lwysj', weight: 49, children: [] },
    { id: 'czgxag', weight: 33, children: [] },
    { id: 'drasjw', weight: 20, children: [] },
    { id: 'pxcjw', weight: 41, children: [] },
    { id: 'hwfzj', weight: 321, children: [] },
    { id: 'ssxqkhq', weight: 67, children: [] },
    { id: 'ndteuz', weight: 46, children: [] },
    { id: 'rwhjmp', weight: 56, children: [] },
    { id: 'xsuxhbq', weight: 1268, children: ['injlqnw', 'vdyhna', 'bzqhk'] },
    { id: 'aufxtq', weight: 14, children: [] },
    { id: 'nknpwkc', weight: 164, children: ['pwyfdan', 'jsbug'] },
    { id: 'dqhoh', weight: 787, children: ['xeypnpr', 'quoqibc', 'wisdd'] },
    { id: 'lqndkq', weight: 54, children: [] },
    { id: 'vabii', weight: 89, children: [] },
    { id: 'pmxzfd', weight: 747, children: ['xnaam', 'iaoxdmm', 'hsywhj'] },
    { id: 'fuexyx', weight: 8, children: [] },
    { id: 'wkxyxtf', weight: 20, children: [] },
    { id: 'bfftnj', weight: 47, children: [] },
    { id: 'hoqti', weight: 6514, children: ['jviven', 'znchnta', 'daxbf'] },
    { id: 'aqrpio', weight: 24, children: [] },
    { id: 'otsyp', weight: 54, children: [] },
    { id: 'vgdsszs', weight: 67, children: [] },
    { id: 'lswutyd', weight: 60, children: [] },
    { id: 'egyfwny', weight: 73, children: [] },
    { id: 'wyiec', weight: 56, children: [] },
    { id: 'qeayjnt', weight: 31, children: ['qbaig', 'yhhnavm', 'eplltu'] },
    { id: 'tjzkwy', weight: 59, children: [] },
    { id: 'vwtsdsf', weight: 251, children: [] },
    { id: 'jzbnq', weight: 78, children: [] },
    { id: 'gtbmrcp', weight: 303, children: [] },
    { id: 'pzoaqn', weight: 94, children: ['ierop', 'llepsqz'] },
    { id: 'oqfiqf', weight: 185, children: ['nirov', 'pyzbqz'] },
    { id: 'kjtwz', weight: 97, children: [] },
    { id: 'gmrkqq', weight: 86, children: [] },
    { id: 'nnkru', weight: 16, children: [] },
    { id: 'nnpvdm', weight: 5, children: [] },
    { id: 'rlgrkq', weight: 9, children: ['uakxuru', 'qvzjgne', 'xhrqzk', 'xatzz', 'hwfzj'] },
    { id: 'oukuy', weight: 85, children: [] },
    { id: 'gsiokvq', weight: 80, children: ['tcbxnrf', 'mfunt', 'tyqnwi', 'yzxqqx', 'ehpdfno', 'oqfiqf', 'clizzo'] },
    { id: 'qluzb', weight: 58, children: [] },
    { id: 'bzorz', weight: 66, children: ['ulgrn', 'kjmvhpa'] },
    { id: 'iqckb', weight: 103, children: ['zuaamot', 'knfath'] },
    { id: 'zikmmr', weight: 87, children: [] },
    { id: 'ugplhkq', weight: 58, children: [] },
    { id: 'vddarvs', weight: 28, children: [] },
    { id: 'agsfbkx', weight: 40, children: [] },
    { id: 'riuwg', weight: 63, children: [] },
    { id: 'mmprixv', weight: 66, children: [] },
    { id: 'pimzjjp', weight: 58, children: ['dresofi', 'riogonj', 'encjlzj', 'rvmntl'] },
    { id: 'eiekcd', weight: 66, children: [] },
    { id: 'gxuovng', weight: 38, children: [] },
    { id: 'vfdulx', weight: 6, children: ['bhnwdot', 'qxqdyx'] },
    { id: 'iizpgi', weight: 84, children: [] },
    { id: 'ctvrea', weight: 54, children: [] },
    { id: 'qscadxk', weight: 28, children: ['hrrqb', 'yxfmelm', 'roojn'] },
    { id: 'qxqdyx', weight: 50, children: [] },
    { id: 'vmkib', weight: 527, children: ['ltccbob', 'lvktp', 'nuoic'] },
    { id: 'mwpejh', weight: 82, children: [] },
    { id: 'gwgchq', weight: 74, children: [] },
    { id: 'hjxzwnq', weight: 97, children: [] },
    { id: 'wisdd', weight: 75, children: ['vsmdkp', 'vzxet', 'jvqfj'] },
    { id: 'bsvoy', weight: 260, children: [] },
    { id: 'pmunsu', weight: 17, children: [] },
    { id: 'kbvzpv', weight: 24, children: ['vybmch', 'nkwisjd', 'ihkcorh', 'bmyme', 'pjamo'] },
    { id: 'xlkvx', weight: 55, children: [] },
    { id: 'uezxhid', weight: 58, children: ['brapqvt', 'cbmkl', 'ijpzp', 'werskvv'] },
    { id: 'qoppte', weight: 52, children: [] },
    { id: 'oxlvr', weight: 60, children: [] },
    { id: 'fuwekd', weight: 55, children: [] },
    { id: 'qgytb', weight: 10, children: [] },
    { id: 'vhbtdr', weight: 5, children: [] },
    { id: 'rtromur', weight: 217, children: ['qbtixl', 'nrphw'] },
    { id: 'mmriyf', weight: 149, children: ['zpkhzqb', 'kmegj'] },
    { id: 'nukpse', weight: 7, children: [] },
    { id: 'hdvcgn', weight: 56, children: ['tjzkwy', 'arouwsi'] },
    { id: 'ghatw', weight: 920, children: ['jezubi', 'kpwvh', 'ywonug'] },
    { id: 'vcoszdq', weight: 31, children: [] },
    { id: 'vcauqo', weight: 166, children: ['hfjpir', 'toaan'] },
    { id: 'fenymdp', weight: 55, children: [] },
    { id: 'rrnkqx', weight: 41, children: [] },
    { id: 'bsythck', weight: 59, children: [] },
    { id: 'uyedi', weight: 1348, children: ['uxhpm', 'rtseps', 'kfkhxg', 'byjcsn'] },
    { id: 'xwydsz', weight: 85, children: [] },
    { id: 'fecwfs', weight: 20, children: [] },
    { id: 'vxfyyd', weight: 60, children: [] },
    { id: 'atxfply', weight: 233, children: ['mckyvtt', 'blfinsi'] },
    { id: 'skrsezs', weight: 93, children: [] },
    { id: 'cncoep', weight: 72, children: ['bgudw', 'qbhvu'] },
    { id: 'awyhreh', weight: 57, children: ['htuuzu', 'eudowc', 'knvxq', 'felksho', 'dcjiqny'] },
    { id: 'kpwvh', weight: 146, children: ['kgbjthh', 'iljkad'] },
    { id: 'gmxdpc', weight: 42, children: [] },
    { id: 'xxleimo', weight: 37, children: [] },
    { id: 'hjbac', weight: 80, children: [] },
    { id: 'twblj', weight: 191, children: ['tbutks', 'indjoox'] },
    { id: 'qbtixl', weight: 7, children: [] },
    { id: 'hubzsdn', weight: 102, children: ['zeiqoz', 'ukbzl'] },
    { id: 'yhadh', weight: 85, children: ['twqkuk', 'fhimhm'] },
    { id: 'injlqnw', weight: 37, children: ['hmrzqlh', 'lmrzi'] },
    { id: 'vwmyqub', weight: 96, children: [] },
    { id: 'omeew', weight: 73, children: ['kbdnbnd', 'rvtus'] },
    { id: 'efsanp', weight: 33, children: ['loaft', 'wkbqm', 'suiagk'] },
    { id: 'frkjf', weight: 114, children: ['ziyive', 'mdcxis'] },
    { id: 'uybuil', weight: 44, children: ['vabii', 'iawzjqd'] },
    { id: 'mjrfrb', weight: 35, children: ['nbhdty', 'lluabej'] },
    { id: 'xhrqzk', weight: 311, children: ['aktnest', 'ixoas'] },
    { id: 'yzxqqx', weight: 66, children: ['acbakwi', 'kqqegw', 'hmxxv'] },
    { id: 'ikyzq', weight: 4037, children: ['oykurjk', 'qfsmgqe', 'biemun', 'zatfti'] },
    { id: 'akght', weight: 55, children: [] },
    { id: 'mbzzt', weight: 877, children: ['kxbmr', 'iivwxhd', 'ddumyx', 'kcxllz'] },
    { id: 'ztpawhz', weight: 52, children: [] },
    { id: 'zzkusct', weight: 77, children: ['qrwzvrb', 'wnjjug'] },
    { id: 'gujegtc', weight: 27, children: ['bddlvs', 'lcjjc'] },
    { id: 'rulju', weight: 14, children: ['dgwrgu', 'iruee', 'awxygg'] },
    { id: 'djodqp', weight: 82, children: ['tqepyv', 'huxtvqc', 'loykzr'] },
    { id: 'vrhltmp', weight: 77, children: [] },
    { id: 'zozcoqd', weight: 487, children: ['alvjc', 'ahism', 'zzkusct', 'tlics', 'rbiarxk'] },
    { id: 'ymxqafr', weight: 93, children: [] },
    { id: 'vmttcwe', weight: 2318, children: ['zumdwwu', 'lvazjz', 'qhiav'] },
    { id: 'prcclw', weight: 18, children: [] },
    { id: 'gicwr', weight: 21, children: [] },
    { id: 'ukwlfcf', weight: 1818, children: ['twblj', 'vpbec', 'wifaf'] },
    { id: 'fvhvq', weight: 32, children: [] },
    { id: 'jvtky', weight: 25, children: [] },
    { id: 'tcjsqp', weight: 96, children: [] },
    { id: 'rdgowwr', weight: 18, children: [] },
    { id: 'yfwwrkp', weight: 156, children: [] },
    { id: 'sejncwk', weight: 626, children: ['sjbqzk', 'acfnchg', 'pzoaqn'] },
    { id: 'edwlns', weight: 34, children: [] },
    { id: 'qiund', weight: 36, children: [] },
    { id: 'cmenpt', weight: 53, children: ['ygmnsct', 'xwydsz'] },
    { id: 'syojg', weight: 99, children: ['mwpejh', 'myoyl'] },
    { id: 'aqbnaso', weight: 91, children: [] },
    { id: 'ovrgyv', weight: 90, children: [] },
    { id: 'ilpjk', weight: 8, children: [] },
    { id: 'fvydfl', weight: 68, children: [] },
    { id: 'fxzqvoh', weight: 231, children: ['rmmxnk', 'vhbtdr', 'xmjpazn', 'sbbbog'] },
    { id: 'quohxia', weight: 68, children: [] },
    { id: 'funabvw', weight: 153, children: ['vkhdfmv', 'igceh'] },
    { id: 'mvxud', weight: 79, children: [] },
    { id: 'rttwi', weight: 35, children: ['tcjsqp', 'amslmyk', 'vwmyqub'] },
    { id: 'yjyyq', weight: 75, children: ['uknqlj', 'trqlfrt'] },
    { id: 'ulgrn', weight: 20, children: [] },
    { id: 'sfpnzbo', weight: 16, children: [] },
    { id: 'iiwpsx', weight: 1466, children: ['coxpxpj', 'tlxdji', 'euoskfi'] },
    { id: 'rhtqj', weight: 249, children: [] },
    { id: 'sdjxpp', weight: 41, children: [] },
    { id: 'qmyohe', weight: 21, children: [] },
    { id: 'bljppq', weight: 30, children: [] },
    { id: 'zskam', weight: 845, children: ['tpabsyz', 'wynyd', 'gtmud', 'aqbnaso'] },
    { id: 'iqhpby', weight: 1769, children: ['zlvjnx', 'iufvcm', 'nfwcuci'] },
    { id: 'brabcb', weight: 99, children: [] },
    { id: 'byvwheg', weight: 82, children: [] },
    { id: 'epstabj', weight: 38, children: [] },
    { id: 'phdeae', weight: 92, children: ['zwcsjgs', 'kdqctmq'] },
    { id: 'xyjsuy', weight: 8, children: [] },
    { id: 'owtswi', weight: 167, children: [] },
    { id: 'htlfqi', weight: 60, children: [] },
    { id: 'ybgdelp', weight: 24, children: [] },
    { id: 'ehwcxy', weight: 63, children: [] },
    { id: 'corcne', weight: 217, children: [] },
    { id: 'tlzlq', weight: 28, children: [] },
    { id: 'hlfmvdt', weight: 12, children: ['meqla', 'yywjam'] },
    { id: 'jwmjz', weight: 5, children: [] },
    { id: 'syhipz', weight: 76, children: ['qwror', 'rzsggfj', 'mjuyo', 'zitvhwp'] },
    { id: 'nfwcuci', weight: 214, children: [] },
    { id: 'pvniw', weight: 42, children: [] },
    { id: 'wknmdh', weight: 836, children: ['thbazqq', 'rpbeiqg', 'lyvdkxe'] },
    { id: 'guvto', weight: 32, children: [] },
    { id: 'isispf', weight: 151, children: ['kvsprca', 'yoiej'] },
    { id: 'hasclc', weight: 46, children: [] },
    { id: 'kxbmr', weight: 116, children: ['jsdbgko', 'mvyzuw'] },
    { id: 'akgfzo', weight: 46, children: ['glblkz', 'lpfahc'] },
    { id: 'jfssr', weight: 14, children: [] },
    { id: 'bxjqibv', weight: 44, children: [] },
    { id: 'jxraf', weight: 15, children: [] },
    { id: 'hfwpcsa', weight: 197, children: [] },
    { id: 'htuuzu', weight: 30, children: ['cmfcqh', 'xvoehjz', 'jabfysb', 'rfllomn', 'mvybmye', 'rttwi'] },
    { id: 'wfcqzm', weight: 95, children: [] },
    { id: 'quolxjw', weight: 84, children: [] },
    { id: 'rergyy', weight: 56, children: [] },
    { id: 'awnafxx', weight: 29, children: [] },
    { id: 'bzuago', weight: 99, children: [] },
    { id: 'ytzdrvj', weight: 28, children: [] },
    { id: 'yoiej', weight: 65, children: [] },
    { id: 'ffijsc', weight: 81, children: [] },
    { id: 'rjqjwjy', weight: 73, children: [] },
    { id: 'wnjjug', weight: 68, children: [] },
    { id: 'ybnsg', weight: 78, children: [] },
    { id: 'ygmnsct', weight: 85, children: [] },
    { id: 'qiaej', weight: 82, children: [] },
    { id: 'gzriygp', weight: 58, children: [] },
    { id: 'zeiqoz', weight: 14, children: [] },
    { id: 'jqgkz', weight: 59, children: [] },
    { id: 'iawzjqd', weight: 89, children: [] },
    { id: 'sxwbzyj', weight: 45, children: [] },
    { id: 'faqxj', weight: 33, children: [] },
    { id: 'gixsbr', weight: 1173, children: ['qvrtwdt', 'wkxlf', 'iiwpsx', 'icspwbg', 'qhfmjrm', 'mspxpr', 'xsuxhbq'] },
    { id: 'ktffksv', weight: 29, children: [] },
    { id: 'mfunt', weight: 165, children: ['quolxjw', 'tgwiasr'] },
    { id: 'lzevbng', weight: 16, children: [] },
    { id: 'azttml', weight: 15, children: [] },
    { id: 'hezkdc', weight: 193, children: ['mpieb', 'voawog'] },
    { id: 'dsoyvp', weight: 55, children: ['pfxoef', 'eiekcd'] },
    { id: 'ildgly', weight: 137, children: ['pvniw', 'ulszlax', 'gtxdtf'] },
    { id: 'paaqws', weight: 214, children: [] },
    { id: 'chcnreg', weight: 33, children: [] },
    { id: 'rpyxxhm', weight: 53, children: [] },
    { id: 'kemxmk', weight: 332, children: ['umtmwow', 'yahsymr'] },
    { id: 'enmxpmj', weight: 64, children: [] },
    { id: 'owjtoo', weight: 63, children: [] },
    { id: 'iaoxdmm', weight: 138, children: ['xyjsuy', 'fzltz'] },
    { id: 'oykurjk', weight: 868, children: ['hkjcnv', 'qscadxk', 'phhumfd'] },
    { id: 'eawwls', weight: 73, children: [] },
    { id: 'kiryhz', weight: 44, children: [] },
    { id: 'janbnmh', weight: 15, children: [] },
    { id: 'sbbbog', weight: 5, children: [] },
    { id: 'sfjyf', weight: 210, children: ['xpdmegi', 'niavkxg', 'eevdo', 'vgkjgy'] },
    { id: 'lwnlk', weight: 47, children: [] },
    { id: 'cthyz', weight: 62, children: [] },
    { id: 'wsrrryh', weight: 64, children: [] },
    { id: 'yahzcyp', weight: 64, children: ['sddoa', 'yscpg'] },
    { id: 'kigsmv', weight: 22, children: [] },
    { id: 'rubvop', weight: 31, children: [] },
    { id: 'ajgvmuy', weight: 80, children: [] },
    { id: 'htwzu', weight: 16, children: [] },
    { id: 'xatzz', weight: 157, children: ['ucahbv', 'qiaej'] },
    { id: 'uzprj', weight: 58, children: [] },
    { id: 'ltceq', weight: 99, children: [] },
    { id: 'dnqdmxc', weight: 79, children: [] },
    { id: 'pmpxq', weight: 13, children: [] },
    { id: 'ebyfpmf', weight: 79, children: [] },
    { id: 'qeuwgn', weight: 36, children: [] },
    { id: 'osbndxb', weight: 23, children: [] },
    { id: 'qunom', weight: 178, children: ['jxhhgvz', 'jjfoqtv'] },
    { id: 'xinxep', weight: 1670, children: ['tewltq', 'qtmvya', 'gixsbr'] },
    { id: 'clrhsr', weight: 19, children: [] },
    { id: 'ierop', weight: 96, children: [] },
    { id: 'wkxlf', weight: 1022, children: ['drwwnwd', 'finxtiu', 'dkwwoa'] },
    { id: 'ogziig', weight: 64, children: [] },
    { id: 'nsqiicp', weight: 27, children: [] },
    { id: 'fkehyrg', weight: 75, children: [] },
    { id: 'zielffk', weight: 23, children: [] },
    { id: 'upatvy', weight: 95, children: [] },
    { id: 'jxhhgvz', weight: 16, children: [] },
    { id: 'swqres', weight: 26, children: [] },
    { id: 'ndmpgss', weight: 89, children: [] },
    { id: 'wzvsi', weight: 69, children: [] },
    { id: 'ihkcorh', weight: 183, children: ['fsjvyxv', 'hmemann'] },
    { id: 'elgvwug', weight: 67, children: [] },
    { id: 'ujzxlx', weight: 98, children: [] },
    { id: 'veiljb', weight: 45, children: [] },
    { id: 'hrrqb', weight: 57, children: [] },
    { id: 'lrlhwat', weight: 22, children: [] },
    { id: 'xlkdss', weight: 7, children: [] },
    { id: 'qibrsjj', weight: 60, children: [] },
    { id: 'ytjheqk', weight: 30, children: [] },
    { id: 'ojnxwzq', weight: 2529, children: ['tvoptyn', 'yysyjbk', 'kqfgnql', 'uwrcgnq'] },
    { id: 'kbfpx', weight: 47, children: [] },
    { id: 'afbnq', weight: 41, children: [] },
    { id: 'yscpg', weight: 46, children: [] },
    { id: 'yatdg', weight: 50, children: [] },
    { id: 'acbakwi', weight: 89, children: [] },
    { id: 'bcedyx', weight: 37, children: [] },
    { id: 'aktnest', weight: 5, children: [] },
    { id: 'fkmpv', weight: 31, children: [] },
    { id: 'kgbjthh', weight: 14, children: [] },
    { id: 'gtmud', weight: 91, children: [] },
    { id: 'alvjc', weight: 139, children: ['qdemebr', 'xxleimo'] },
    { id: 'yedvssr', weight: 205, children: ['fvkew', 'gicwr'] },
    { id: 'ejlya', weight: 66, children: [] },
    { id: 'mhkrny', weight: 672, children: ['bezoxx', 'haano', 'pggrr'] },
    { id: 'edfxg', weight: 74, children: [] },
    { id: 'bmyme', weight: 95, children: ['wsdqchf', 'yhtpdwu'] },
    { id: 'uedozkm', weight: 5333, children: ['tntns', 'mkslglr', 'zgkxkj', 'sejncwk'] },
    { id: 'hsywhj', weight: 154, children: [] },
    { id: 'licst', weight: 9, children: [] },
    { id: 'gtbocpw', weight: 60, children: [] },
    { id: 'vdwutc', weight: 90, children: [] },
    { id: 'ulkdq', weight: 82, children: [] },
    { id: 'ceutto', weight: 21, children: [] },
    { id: 'sivsece', weight: 73, children: [] },
    { id: 'tntns', weight: 1094, children: ['djodqp', 'ixuvbk', 'hubzsdn'] },
    { id: 'qhfmjrm', weight: 1628, children: ['xmhdsio', 'myzut', 'dfupxk'] },
    { id: 'rzsggfj', weight: 317, children: ['udlhalx', 'narnhty'] },
    { id: 'hlshpkq', weight: 99, children: ['zpuwyqp', 'zqaxyz'] },
    { id: 'ijpzp', weight: 78, children: [] },
    { id: 'qtmvya', weight: 14, children: ['gsiokvq', 'wanxt', 'kskkjn', 'adtpk', 'iqhpby', 'pcehxbx'] },
    { id: 'ktoxuar', weight: 83, children: ['eawwls', 'tvfptpz'] },
    { id: 'uwehdau', weight: 55, children: [] },
    { id: 'advjges', weight: 20, children: [] },
    { id: 'iuubp', weight: 62, children: [] },
    { id: 'encjlzj', weight: 49, children: ['ltceq', 'brabcb', 'uyoez'] },
    { id: 'pabkgnq', weight: 10, children: [] },
    { id: 'ulxscm', weight: 35, children: [] },
    { id: 'rcbhgw', weight: 832, children: ['jrott', 'hcvwov', 'akgfzo'] },
    { id: 'nevhjg', weight: 17, children: [] },
    { id: 'agtab', weight: 41, children: ['ztpawhz', 'dsiixv', 'gipbso', 'nholw'] },
    { id: 'xjbtfms', weight: 33, children: [] },
    { id: 'mfcutqz', weight: 219, children: ['ncbrxsy', 'bnwotj'] },
    { id: 'txhxoib', weight: 240, children: ['qgytb', 'pabkgnq'] },
    { id: 'miwjfr', weight: 20, children: [] },
    { id: 'vkmxs', weight: 75, children: [] },
    { id: 'hidzw', weight: 55, children: [] },
    { id: 'whjbc', weight: 54, children: [] },
    { id: 'ivhtlxa', weight: 17, children: [] },
    { id: 'jgylf', weight: 98, children: [] },
    { id: 'iydqii', weight: 55, children: [] },
    { id: 'gkitfsr', weight: 23, children: [] },
    { id: 'carfsnj', weight: 79, children: [] },
    { id: 'pxkzk', weight: 5, children: [] },
    { id: 'wlwnand', weight: 87, children: [] },
    { id: 'khdzsr', weight: 73, children: [] },
    { id: 'tqepyv', weight: 16, children: [] },
    { id: 'gsdzpjh', weight: 40, children: [] },
    { id: 'wnmnz', weight: 290, children: ['rywggm', 'hpfmhy', 'frkjf', 'ojpghb', 'wgjst', 'ivldghm'] },
    { id: 'msyvs', weight: 32, children: ['kyhezqn', 'dkegbrt', 'enogehk'] },
    { id: 'uusec', weight: 41, children: [] },
    { id: 'ufdbsy', weight: 132, children: ['mrmuat', 'seuaftr'] },
    { id: 'vwupkmh', weight: 53, children: [] },
    { id: 'pthnz', weight: 34, children: ['fjkfpm', 'uedozkm', 'hoqti', 'efgdfa'] },
    { id: 'jzwusi', weight: 188, children: ['edagh', 'xrknksz', 'syxdt', 'xeege'] },
    { id: 'npblyaq', weight: 35, children: ['mnfknb', 'jdjkbwr', 'aixwgk', 'ducdc'] },
    { id: 'mdvnu', weight: 42, children: [] },
    { id: 'qcglune', weight: 68, children: [] },
    { id: 'jafsqqu', weight: 41, children: [] },
    { id: 'nderndc', weight: 63, children: [] },
    { id: 'qtshuo', weight: 44, children: [] },
    { id: 'twqkuk', weight: 66, children: [] },
    { id: 'fcdutzs', weight: 8, children: [] },
    { id: 'olgmto', weight: 702, children: ['lbwgsap', 'jakmbx', 'aufwfrp', 'osnpbou'] },
    { id: 'pfekvok', weight: 34, children: [] },
    { id: 'cbmkr', weight: 93, children: ['pjzcs', 'pavtnxe', 'nsoju'] },
    { id: 'igceh', weight: 36, children: [] },
    { id: 'blvyrzh', weight: 10, children: ['vdwutc', 'cneww', 'mkykc', 'ovrgyv'] },
    { id: 'mtxzek', weight: 136, children: ['kfefhun', 'wnpkwy'] },
    { id: 'bsxtebe', weight: 71, children: ['idnsypp', 'iqfnj'] },
    { id: 'bntzksk', weight: 37289, children: ['vmttcwe', 'ukwlfcf', 'zzpevgd'] },
    { id: 'eudowc', weight: 1052, children: ['mjrfrb', 'uxsisng', 'yawmlbb', 'ktoxuar'] },
    { id: 'mcghosj', weight: 41, children: [] },
    { id: 'ojpghb', weight: 156, children: ['prcclw', 'gytzi'] },
    { id: 'osrdt', weight: 79, children: [] },
    { id: 'vqrrii', weight: 60, children: ['zrgqfb', 'ffijsc'] },
    { id: 'wkgouh', weight: 53, children: [] },
    { id: 'nsvwcl', weight: 90, children: [] },
    { id: 'eumefa', weight: 84, children: [] },
    { id: 'zuaamot', weight: 32, children: [] },
    { id: 'lxdji', weight: 8, children: [] },
    { id: 'zeebqts', weight: 24, children: [] },
    { id: 'yktye', weight: 24, children: [] },
    { id: 'wswnja', weight: 117, children: ['fnkrew', 'mcmzs'] },
    { id: 'vtqzf', weight: 17, children: [] },
    { id: 'kmnzz', weight: 5, children: ['wtsqx', 'ocqrpkf', 'hasclc', 'kqdseyh'] },
    { id: 'ednlrw', weight: 56, children: [] },
    { id: 'yxfmelm', weight: 57, children: [] },
    { id: 'fgeup', weight: 36, children: [] },
    { id: 'oiufrau', weight: 43, children: ['ajgvmuy', 'kxzwel', 'hjbac'] },
    { id: 'bdvtnul', weight: 26, children: [] },
    { id: 'xayqwyj', weight: 168, children: ['wvdswpz', 'fvaeyq'] },
    { id: 'vzxet', weight: 60, children: [] },
    { id: 'cvvkno', weight: 56, children: [] },
    { id: 'wctihs', weight: 31, children: ['ikicwez', 'wzvsi'] },
    { id: 'cpzwgk', weight: 209, children: ['lwnlk', 'xvudg'] },
    { id: 'fsoqc', weight: 24, children: [] },
    { id: 'hkkzpzh', weight: 14, children: [] },
    { id: 'wfeurd', weight: 165, children: ['nlrbcxx', 'kbbwe'] },
    { id: 'klexq', weight: 30, children: [] },
    { id: 'ebjgfh', weight: 34, children: [] },
    { id: 'vctupmx', weight: 42, children: [] },
    { id: 'psrup', weight: 53, children: [] },
    { id: 'ngiol', weight: 95, children: [] },
    { id: 'kryvxoc', weight: 18, children: [] },
    { id: 'tzkgrjf', weight: 54, children: [] },
    { id: 'gcrugvi', weight: 62, children: [] },
    { id: 'jxhhc', weight: 17, children: [] },
    { id: 'wntfmtn', weight: 254, children: ['faqxj', 'qzgdlb', 'uurqa'] },
    { id: 'wuyjdn', weight: 95, children: [] },
    { id: 'dbrcg', weight: 11, children: [] },
    { id: 'dcwcs', weight: 42, children: [] },
    { id: 'dsuchz', weight: 88, children: [] },
    { id: 'hlykzp', weight: 31, children: [] },
    { id: 'pwyfdan', weight: 85, children: [] },
    { id: 'hmemann', weight: 27, children: [] },
    { id: 'yjmjnm', weight: 77, children: [] },
    { id: 'cjcytbb', weight: 55, children: [] },
    { id: 'sutzt', weight: 169, children: ['fpdoney', 'nnkru', 'sfpnzbo'] },
    { id: 'lvazjz', weight: 39, children: ['zinjsj', 'abjmd'] },
    { id: 'bfozr', weight: 43, children: [] },
    { id: 'gfvzrt', weight: 84, children: [] },
    { id: 'wanxt', weight: 1603, children: ['lgqwxgu', 'shwsf', 'zvnzep', 'jwrmi'] },
    { id: 'fntaap', weight: 43, children: [] },
    { id: 'dfupxk', weight: 91, children: [] },
    { id: 'uxsisng', weight: 95, children: ['elgvwug', 'ssxqkhq'] },
    { id: 'rflrj', weight: 181, children: ['niklue', 'yjcggu'] },
    { id: 'narnhty', weight: 26, children: [] },
    { id: 'ziyive', weight: 39, children: [] },
    { id: 'tkvip', weight: 279, children: [] },
    { id: 'xjjvneg', weight: 19, children: [] },
    { id: 'toaan', weight: 19, children: [] },
    { id: 'tgoztyw', weight: 201, children: ['yrnjhqc', 'rzldn'] },
    { id: 'nrphw', weight: 7, children: [] },
    { id: 'bhnwdot', weight: 50, children: [] },
    { id: 'negxuk', weight: 217, children: ['nsqiicp', 'xsvage'] },
    { id: 'tyqnwi', weight: 155, children: ['kigpl', 'iwkotv'] },
    { id: 'qbhyq', weight: 98, children: [] },
    { id: 'qmeawpu', weight: 22, children: [] },
    { id: 'xjejd', weight: 88, children: [] },
    { id: 'pvbgvb', weight: 41, children: [] },
    { id: 'snsyzbk', weight: 20, children: [] },
    { id: 'vkile', weight: 164, children: ['pdkfixk', 'ufpdyq', 'lrlhwat', 'kigsmv'] },
    { id: 'jdazgj', weight: 17, children: [] },
    { id: 'cdaazt', weight: 54, children: [] },
    { id: 'qtcnfy', weight: 50, children: [] },
    { id: 'gwyrtw', weight: 52, children: [] },
    { id: 'sgznbm', weight: 50, children: [] },
    { id: 'gkqxb', weight: 65, children: ['ioyealn', 'rqeftjw'] },
    { id: 'mgoym', weight: 83, children: ['kslvs', 'snyio'] },
    { id: 'cneww', weight: 90, children: [] },
    { id: 'fixqj', weight: 116, children: ['ybzqe', 'nhcmgrr', 'nevhjg'] },
    { id: 'kjmvhpa', weight: 20, children: [] },
    { id: 'sntbr', weight: 55, children: [] },
    { id: 'bnwotj', weight: 15, children: [] },
    { id: 'xvudg', weight: 47, children: [] },
    { id: 'ltyxiwk', weight: 53, children: [] },
    { id: 'brapqvt', weight: 78, children: [] },
    { id: 'zrmzpo', weight: 95, children: [] },
    { id: 'xcdswr', weight: 85, children: [] },
    { id: 'erngeah', weight: 44, children: [] },
    { id: 'zvogn', weight: 8, children: [] },
    { id: 'ranlxct', weight: 59, children: [] },
    { id: 'oztxjfl', weight: 239, children: ['eukyl', 'pjpbcq'] },
    { id: 'bcrso', weight: 24, children: [] },
    { id: 'ogtxa', weight: 89, children: ['iuubp', 'gcrugvi', 'cthyz', 'zzlocxd'] },
    { id: 'utpyp', weight: 35, children: [] },
    { id: 'rmmxnk', weight: 5, children: [] },
    { id: 'nogoyp', weight: 70, children: ['rdgowwr', 'kryvxoc'] },
    { id: 'afqwh', weight: 30, children: [] },
    { id: 'nedjj', weight: 54, children: [] },
    { id: 'lyvdkxe', weight: 42, children: ['ssblis', 'gmrkqq'] },
    { id: 'ybzqe', weight: 17, children: [] },
    { id: 'bnvjfq', weight: 34, children: [] },
    { id: 'sklld', weight: 24, children: [] },
    { id: 'eqkio', weight: 2131, children: ['eefmcrp', 'cmenpt', 'wswnja'] },
    { id: 'qypsl', weight: 54, children: [] },
    { id: 'wcfykko', weight: 60, children: [] },
    { id: 'luiiv', weight: 898, children: ['vgnkq', 'coenr', 'paaqws'] },
    { id: 'mjpmw', weight: 101, children: ['lomxh', 'rqvifq'] },
    { id: 'wswwck', weight: 40, children: ['zmdvl', 'yatdg', 'sgznbm'] },
    { id: 'yjcggu', weight: 18, children: [] },
    { id: 'pjpbcq', weight: 22, children: [] },
    { id: 'yahsymr', weight: 30, children: [] },
    { id: 'liwvq', weight: 1960, children: ['axqifwm', 'qunom', 'euxvn', 'efsanp'] },
    { id: 'euoskfi', weight: 135, children: ['nnpvdm', 'jwmjz'] },
    { id: 'hpfmhy', weight: 176, children: ['fuexyx', 'fcdutzs'] },
    { id: 'jczkx', weight: 55, children: [] },
    { id: 'jvwfxp', weight: 330, children: ['cvcyykp', 'hlykzp'] },
    { id: 'pyscsi', weight: 64, children: [] },
    { id: 'jevfpj', weight: 65, children: [] },
    { id: 'zitvhwp', weight: 75, children: ['tpbcg', 'ujzxlx', 'qbhyq'] },
    { id: 'sndject', weight: 5, children: [] },
    { id: 'aufwfrp', weight: 53, children: ['mmprixv', 'ejlya'] },
    { id: 'riogonj', weight: 346, children: [] },
    { id: 'dhecgkl', weight: 73, children: [] },
    { id: 'eevdo', weight: 16, children: [] },
    { id: 'kslvs', weight: 42, children: [] },
    { id: 'zpuktmx', weight: 37, children: [] },
    { id: 'nbkzscx', weight: 9, children: [] },
    { id: 'pbvcu', weight: 73, children: [] },
    { id: 'zwymlsj', weight: 118, children: ['tcpvyfj', 'rtiaapt', 'xikbq', 'gldvef'] },
    { id: 'fzbwmsz', weight: 187, children: ['dbrcg', 'wkkkv', 'mznsk', 'etkzf'] },
    { id: 'tmtfhr', weight: 30, children: [] },
    { id: 'eukyl', weight: 22, children: [] },
    { id: 'hmugaom', weight: 156, children: [] },
    { id: 'ixuvbk', weight: 130, children: [] },
    { id: 'santsu', weight: 76, children: [] },
    { id: 'buplpb', weight: 26, children: ['negxuk', 'imuhew', 'izssdb'] },
    { id: 'imuhew', weight: 77, children: ['yauryvu', 'kjtwz'] },
    { id: 'niklue', weight: 18, children: [] },
    { id: 'zuzhmf', weight: 137, children: ['pbvcu', 'sivsece'] },
    { id: 'lgqwxgu', weight: 202, children: [] },
    { id: 'emxwr', weight: 262, children: ['nedjj', 'hwfcy'] },
    { id: 'iqfnj', weight: 94, children: [] },
    { id: 'ixyeq', weight: 273, children: ['pxkzk', 'ylfvgv'] },
    { id: 'wvgzlw', weight: 87, children: ['hidzw', 'vofrtf', 'yvllxxw'] },
    { id: 'kbbwe', weight: 41, children: [] },
    { id: 'jcsjaxj', weight: 2792, children: ['buplpb', 'slntf', 'kqohkg'] },
    { id: 'tlxdji', weight: 145, children: [] },
    { id: 'hgaoiz', weight: 283, children: [] },
    { id: 'tgwiasr', weight: 84, children: [] },
    { id: 'ewyrp', weight: 259, children: ['jevqne', 'ilpjk', 'kmpmdb'] },
    { id: 'kmegj', weight: 50, children: [] },
    { id: 'axqifwm', weight: 98, children: ['dasmiiw', 'wyiec'] },
    { id: 'jrrhzc', weight: 5, children: [] },
    { id: 'cftggo', weight: 20, children: [] },
    { id: 'xvoyybs', weight: 56, children: ['ygvvvq', 'kemxmk', 'jkfrln', 'arjgn', 'fvsitx', 'lfrfa', 'jvwfxp'] },
    { id: 'daiaot', weight: 60, children: [] },
    { id: 'avemxf', weight: 63, children: [] },
    { id: 'yzpyzu', weight: 41, children: [] },
    { id: 'wtbst', weight: 73, children: [] },
    { id: 'seuaftr', weight: 21, children: [] },
    { id: 'dgwrgu', weight: 89, children: [] },
    { id: 'kpffozq', weight: 27, children: [] },
    { id: 'qoeviy', weight: 129, children: ['yxvmxzg', 'bfxvxpl'] },
    { id: 'uwprsvh', weight: 1502, children: ['qjkkohe', 'pctkyat'] },
    { id: 'ldvcrw', weight: 299, children: ['clrhsr', 'elmmtp'] },
    { id: 'yywjam', weight: 86, children: [] },
    { id: 'elmmtp', weight: 19, children: [] },
    { id: 'coenr', weight: 56, children: ['edyohkw', 'vspquqe'] },
    { id: 'khixwdd', weight: 54, children: ['vxfyyd', 'dltbolj', 'htlfqi'] },
    { id: 'jsdbgko', weight: 73, children: [] },
    { id: 'llepsqz', weight: 96, children: [] },
    { id: 'smqtcaj', weight: 250, children: ['daiaot', 'lswutyd'] },
    { id: 'thbazqq', weight: 180, children: ['pmunsu', 'vtqzf'] },
    { id: 'kaitdu', weight: 98, children: [] },
    { id: 'fvaeyq', weight: 34, children: [] },
    { id: 'glblkz', weight: 97, children: [] },
    { id: 'vmofl', weight: 39, children: ['eumefa', 'gfvzrt'] },
    { id: 'dqktd', weight: 95, children: [] },
    { id: 'mwvbcqg', weight: 58, children: [] },
    { id: 'gbwfjf', weight: 777, children: ['tkvip', 'mbcwjt', 'sbimooe'] },
    { id: 'hmxxv', weight: 89, children: [] },
    { id: 'wynyd', weight: 91, children: [] },
    { id: 'jdjkbwr', weight: 41, children: [] },
    { id: 'elxccty', weight: 54, children: ['fvydfl', 'qcglune'] },
    { id: 'bnmuprs', weight: 41, children: [] },
    { id: 'kgfudu', weight: 45, children: ['otsyp', 'sdixs', 'whjbc', 'cdaazt'] },
    { id: 'hfjtksr', weight: 39, children: [] },
    { id: 'tlgdija', weight: 81, children: ['fntaap', 'zlxlwv'] },
    { id: 'qrwzvrb', weight: 68, children: [] },
    { id: 'nchgm', weight: 49, children: [] },
    { id: 'gofjvi', weight: 67, children: [] },
    { id: 'jjfoqtv', weight: 16, children: [] },
    { id: 'tfbqaoe', weight: 53, children: [] },
    { id: 'zzqtmxd', weight: 116, children: ['fecwfs', 'eigsdc'] },
    { id: 'qhktzou', weight: 75, children: [] },
    { id: 'wydtqax', weight: 45, children: [] },
    { id: 'ytyhmux', weight: 84, children: [] },
    { id: 'qqkqhzb', weight: 274, children: [] },
    { id: 'trqlfrt', weight: 92, children: [] },
    { id: 'eivaf', weight: 370, children: [] },
    { id: 'njlaepf', weight: 47, children: [] },
    { id: 'bkmepbs', weight: 46, children: [] },
    { id: 'mpieb', weight: 34, children: [] },
    { id: 'sbimooe', weight: 89, children: ['dqktd', 'bnmsz'] },
    { id: 'dltbolj', weight: 60, children: [] },
    { id: 'lvktp', weight: 32, children: ['prnno', 'qxsjs', 'wuyjdn'] },
    { id: 'lcius', weight: 54, children: [] },
    { id: 'mxelfv', weight: 75, children: [] },
    { id: 'hrwtz', weight: 17, children: ['mocpa', 'fixysjm', 'cjkieim'] },
    { id: 'jzcstbe', weight: 236, children: [] },
    { id: 'mikalda', weight: 35, children: [] },
    { id: 'xrknksz', weight: 12, children: [] },
    { id: 'knfath', weight: 32, children: [] },
    { id: 'pmssap', weight: 99, children: [] },
    { id: 'eefmcrp', weight: 209, children: ['nukpse', 'xlkdss'] },
    { id: 'nkwisjd', weight: 149, children: ['pfltnc', 'fblsn'] },
    { id: 'ragcph', weight: 38, children: [] },
    { id: 'eubjf', weight: 58, children: [] },
    { id: 'snyio', weight: 42, children: [] },
    { id: 'zquvn', weight: 108, children: ['nvrpd', 'dlrznye'] },
    { id: 'uakxuru', weight: 169, children: ['zhpdhat', 'uymdj'] },
    { id: 'egrit', weight: 73, children: [] },
    { id: 'dlvttmo', weight: 95, children: [] },
    { id: 'xikbq', weight: 18, children: [] },
    { id: 'xgmrufk', weight: 56, children: [] },
    { id: 'cbmkl', weight: 78, children: [] },
    { id: 'jqwaifx', weight: 24, children: [] },
    { id: 'qowepn', weight: 33, children: [] },
    { id: 'clizzo', weight: 227, children: ['dfrzb', 'zjxjhwc'] },
    { id: 'tbakk', weight: 935, children: ['wctihs', 'vszpkfs', 'iqtdzrh'] },
    { id: 'qvzjgne', weight: 36, children: ['dlvttmo', 'wfcqzm', 'mfslhp'] },
    { id: 'mvybmye', weight: 207, children: ['awnafxx', 'xqrrpu', 'ktffksv', 'csbgxs'] },
    { id: 'mkslglr', weight: 189, children: ['dmkhzgg', 'sykmuwo', 'bsxtebe', 'yjyyq', 'znmav'] },
    { id: 'jkfrln', weight: 342, children: ['jbhohbx', 'jvtky'] },
    { id: 'znswber', weight: 40, children: [] },
    { id: 'rqvifq', weight: 53, children: [] },
    { id: 'fnkrew', weight: 53, children: [] },
    { id: 'jabfysb', weight: 91, children: ['gzriygp', 'eubjf', 'qluzb', 'ugplhkq'] },
    { id: 'dresofi', weight: 346, children: [] },
    { id: 'zpkhzqb', weight: 50, children: [] },
    { id: 'hwraaxu', weight: 89, children: ['majskr', 'nchgm'] },
    { id: 'uebmnqa', weight: 88, children: ['ymxqafr', 'skrsezs'] },
    { id: 'qeoetnp', weight: 173, children: ['evvfcyi', 'pmpxq'] },
    { id: 'sddoa', weight: 46, children: [] },
    { id: 'qdemebr', weight: 37, children: [] },
    { id: 'kobwktw', weight: 62, children: [] },
    { id: 'fogmaih', weight: 75, children: [] },
    { id: 'wgevvca', weight: 79, children: [] },
    { id: 'phhumfd', weight: 35, children: ['ulkdq', 'ulvbf'] },
    { id: 'zpuwyqp', weight: 59, children: [] },
    { id: 'txdprek', weight: 83, children: ['gsbmh', 'iizpgi'] },
    { id: 'cqmvs', weight: 14, children: ['bntzksk', 'mvpqv', 'pthnz', 'xinxep', 'qnhvjec', 'znztzxd', 'silwwua'] },
    { id: 'wazlg', weight: 92, children: [] },
    { id: 'unpdcwm', weight: 153, children: ['yktye', 'sklld', 'tdrdq'] },
    { id: 'uknqlj', weight: 92, children: [] },
    { id: 'qwror', weight: 369, children: [] },
    { id: 'awxygg', weight: 89, children: [] },
    { id: 'uwrcgnq', weight: 1176, children: ['uybuil', 'vqrrii', 'arejh'] },
    { id: 'nvrpd', weight: 83, children: [] },
    { id: 'znuldtj', weight: 30, children: [] },
    { id: 'wxyaqte', weight: 27, children: [] },
    { id: 'xbywgft', weight: 55, children: [] },
    { id: 'iwidsj', weight: 95, children: [] },
    { id: 'kcxllz', weight: 43, children: ['mdlubuq', 'dhecgkl', 'uvpwrf'] },
    { id: 'arejh', weight: 188, children: ['lbkrk', 'jxhhc'] },
    { id: 'qbaig', weight: 84, children: [] },
    { id: 'mvpqv', weight: 5522, children: ['ojnxwzq', 'qlchz', 'awyhreh', 'ikyzq'] },
    { id: 'lpfahc', weight: 97, children: [] },
    { id: 'fadkfic', weight: 36, children: [] },
    { id: 'xvwgxm', weight: 63, children: ['wazlg', 'vmkfcpw'] },
    { id: 'tewltq', weight: 4134, children: ['cviwy', 'wknmdh', 'bcnqhw', 'vmkib', 'ezaobs', 'gewlsr', 'yevywe'] },
    { id: 'rfwgt', weight: 78, children: [] },
    { id: 'wsjizsy', weight: 33, children: ['bsiwtqq', 'uzprj', 'mwvbcqg'] },
    { id: 'rbbkdj', weight: 191, children: ['rjqjwjy', 'egrit'] },
    { id: 'cwwwcge', weight: 20, children: [] },
    { id: 'ejbtu', weight: 58, children: ['qnepf', 'dsuchz'] },
    { id: 'hefjuue', weight: 24, children: [] },
    { id: 'coxpxpj', weight: 5, children: ['cbgnzhz', 'uofuvf'] },
    { id: 'nhcmgrr', weight: 17, children: [] },
    { id: 'iktev', weight: 194, children: ['chcnreg', 'olnfe'] },
    { id: 'vhnnnv', weight: 79, children: [] },
    { id: 'kmwkft', weight: 88, children: ['edfxg', 'xaovjvs'] },
    { id: 'kdqctmq', weight: 7, children: [] },
    { id: 'slntf', weight: 309, children: ['dmxlfzb', 'phdeae', 'vfdulx', 'bzorz', 'nogoyp'] },
    { id: 'ohqivu', weight: 82, children: ['yjmjnm', 'taxky'] },
    { id: 'lqasevp', weight: 26, children: [] },
    { id: 'roojn', weight: 57, children: [] },
    { id: 'ojrixty', weight: 97, children: [] },
    { id: 'xmjpazn', weight: 5, children: [] },
    { id: 'salxel', weight: 5, children: [] },
    { id: 'lhlgijf', weight: 54, children: [] },
    { id: 'zatfti', weight: 60, children: ['phkzo', 'ghqixh', 'rulju', 'ksnxlcl', 'isispf'] },
    { id: 'znmav', weight: 95, children: ['byvwheg', 'kefudoj'] },
    { id: 'myzut', weight: 91, children: [] },
    { id: 'cekchxh', weight: 59, children: ['lcwqdxx', 'nkdbmjv', 'pfekvok'] },
    { id: 'ukbzl', weight: 14, children: [] },
    { id: 'bwrpc', weight: 41, children: ['jzbnq', 'fezoyaj', 'birtjxh', 'fcjjqev'] },
    { id: 'ytadaxm', weight: 26, children: ['nlkwsrn', 'qtcnfy'] },
    { id: 'qlryl', weight: 10, children: [] },
    { id: 'vytlfm', weight: 33, children: [] },
    { id: 'jswxshd', weight: 127, children: ['teapi', 'ugssydn'] },
    { id: 'emqwt', weight: 50, children: [] },
    { id: 'ugssydn', weight: 35, children: [] },
    { id: 'iumsmx', weight: 20, children: [] },
    { id: 'kigpl', weight: 89, children: [] },
    { id: 'cdfij', weight: 68, children: [] },
    { id: 'esmbu', weight: 8, children: [] },
    { id: 'izpta', weight: 84, children: [] },
    { id: 'jviven', weight: 416, children: ['gujegtc', 'owtswi', 'haayebg', 'yjcevge', 'mgoym', 'iqckb', 'gkqxb'] },
    { id: 'qhiav', weight: 99, children: [] },
    { id: 'ixoas', weight: 5, children: [] },
    { id: 'dmxlfzb', weight: 16, children: ['afqwh', 'klexq', 'tiyvea'] },
    { id: 'redeub', weight: 57, children: ['hxhguzh', 'vkmxs'] },
    { id: 'fymyi', weight: 35, children: [] },
    { id: 'mdcxis', weight: 39, children: [] },
    { id: 'lcjjc', weight: 70, children: [] },
    { id: 'acfnchg', weight: 246, children: ['advjges', 'cftggo'] },
    { id: 'ldkojcj', weight: 8, children: [] },
    { id: 'nwlkk', weight: 84, children: [] },
    { id: 'kzocw', weight: 2306, children: ['umsrz', 'mbzzt', 'uilvahq'] },
    { id: 'meqla', weight: 86, children: [] },
    { id: 'drwwnwd', weight: 139, children: ['vrhltmp', 'njaig'] },
    { id: 'vspquqe', weight: 79, children: [] },
    { id: 'uymdj', weight: 76, children: [] },
    { id: 'eutun', weight: 192, children: ['iumsmx', 'snsyzbk', 'wkxyxtf'] },
    { id: 'ezaobs', weight: 434, children: ['lngdxkd', 'brmvw', 'hdvcgn', 'ufdbsy', 'qsxqwub', 'rkswk'] },
    { id: 'iljkad', weight: 14, children: [] },
    { id: 'ryeiot', weight: 41, children: [] },
    { id: 'mwhraq', weight: 86, children: ['lwysj', 'lmgxknk'] },
];

module.exports = DATA;
