const INIT = 'init';
const GIVE = 'give';

module.exports = {
	INIT,
	GIVE,
	sampleInput: [
		{ action: INIT, value: 5, goesTo: { bot: 2 } },
		{
			action: GIVE,
			from: { bot: 2 },
			lowTo: { bot: 1 },
			highTo: { bot: 0 },
		},
		{ action: INIT, value: 3, goesTo: { bot: 1 } },
		{
			action: GIVE,
			from: { bot: 1 },
			lowTo: { output: 1 },
			highTo: { bot: 0 },
		},
		{
			action: GIVE,
			from: { bot: 0 },
			lowTo: { output: 2 },
			highTo: { output: 0 },
		},
		{ action: INIT, value: 2, goesTo: { bot: 2 } },
	],
	input: [
		{ action: INIT, value: 23, goesTo: { bot: 208 } },
		{
			action: GIVE,
			from: { bot: 125 },
			lowTo: { bot: 58 },
			highTo: { bot: 57 },
		},
		{ action: INIT, value: 13, goesTo: { bot: 161 } },
		{
			action: GIVE,
			from: { bot: 178 },
			lowTo: { bot: 88 },
			highTo: { bot: 172 },
		},
		{ action: INIT, value: 59, goesTo: { bot: 128 } },
		{
			action: GIVE,
			from: { bot: 173 },
			lowTo: { bot: 83 },
			highTo: { bot: 202 },
		},
		{
			action: GIVE,
			from: { bot: 189 },
			lowTo: { bot: 35 },
			highTo: { bot: 55 },
		},
		{
			action: GIVE,
			from: { bot: 123 },
			lowTo: { bot: 90 },
			highTo: { bot: 169 },
		},
		{
			action: GIVE,
			from: { bot: 148 },
			lowTo: { bot: 101 },
			highTo: { bot: 134 },
		},
		{
			action: GIVE,
			from: { bot: 36 },
			lowTo: { bot: 78 },
			highTo: { bot: 105 },
		},
		{
			action: GIVE,
			from: { bot: 196 },
			lowTo: { bot: 171 },
			highTo: { bot: 45 },
		},
		{
			action: GIVE,
			from: { bot: 157 },
			lowTo: { bot: 179 },
			highTo: { bot: 87 },
		},
		{
			action: GIVE,
			from: { bot: 124 },
			lowTo: { bot: 25 },
			highTo: { bot: 80 },
		},
		{
			action: GIVE,
			from: { bot: 55 },
			lowTo: { bot: 99 },
			highTo: { bot: 201 },
		},
		{ action: INIT, value: 17, goesTo: { bot: 4 } },
		{
			action: GIVE,
			from: { bot: 127 },
			lowTo: { bot: 118 },
			highTo: { bot: 142 },
		},
		{
			action: GIVE,
			from: { bot: 9 },
			lowTo: { bot: 61 },
			highTo: { bot: 198 },
		},
		{
			action: GIVE,
			from: { bot: 71 },
			lowTo: { bot: 86 },
			highTo: { bot: 96 },
		},
		{
			action: GIVE,
			from: { bot: 86 },
			lowTo: { bot: 98 },
			highTo: { bot: 149 },
		},
		{
			action: GIVE,
			from: { bot: 176 },
			lowTo: { bot: 89 },
			highTo: { bot: 171 },
		},
		{
			action: GIVE,
			from: { bot: 38 },
			lowTo: { bot: 107 },
			highTo: { bot: 63 },
		},
		{
			action: GIVE,
			from: { bot: 67 },
			lowTo: { bot: 77 },
			highTo: { bot: 7 },
		},
		{
			action: GIVE,
			from: { bot: 131 },
			lowTo: { output: 6 },
			highTo: { bot: 151 },
		},
		{
			action: GIVE,
			from: { bot: 97 },
			lowTo: { bot: 33 },
			highTo: { bot: 16 },
		},
		{
			action: GIVE,
			from: { bot: 89 },
			lowTo: { bot: 27 },
			highTo: { bot: 36 },
		},
		{
			action: GIVE,
			from: { bot: 29 },
			lowTo: { bot: 185 },
			highTo: { bot: 11 },
		},
		{
			action: GIVE,
			from: { bot: 92 },
			lowTo: { bot: 189 },
			highTo: { bot: 122 },
		},
		{
			action: GIVE,
			from: { bot: 77 },
			lowTo: { output: 7 },
			highTo: { bot: 191 },
		},
		{
			action: GIVE,
			from: { bot: 14 },
			lowTo: { bot: 152 },
			highTo: { bot: 179 },
		},
		{
			action: GIVE,
			from: { bot: 49 },
			lowTo: { bot: 76 },
			highTo: { bot: 64 },
		},
		{ action: INIT, value: 2, goesTo: { bot: 155 } },
		{
			action: GIVE,
			from: { bot: 159 },
			lowTo: { bot: 182 },
			highTo: { bot: 49 },
		},
		{
			action: GIVE,
			from: { bot: 129 },
			lowTo: { bot: 141 },
			highTo: { bot: 40 },
		},
		{
			action: GIVE,
			from: { bot: 50 },
			lowTo: { output: 1 },
			highTo: { bot: 47 },
		},
		{
			action: GIVE,
			from: { bot: 93 },
			lowTo: { output: 5 },
			highTo: { bot: 167 },
		},
		{
			action: GIVE,
			from: { bot: 112 },
			lowTo: { output: 13 },
			highTo: { bot: 51 },
		},
		{
			action: GIVE,
			from: { bot: 165 },
			lowTo: { bot: 163 },
			highTo: { bot: 123 },
		},
		{
			action: GIVE,
			from: { bot: 13 },
			lowTo: { bot: 75 },
			highTo: { bot: 74 },
		},
		{
			action: GIVE,
			from: { bot: 141 },
			lowTo: { bot: 178 },
			highTo: { bot: 207 },
		},
		{
			action: GIVE,
			from: { bot: 37 },
			lowTo: { bot: 42 },
			highTo: { bot: 139 },
		},
		{ action: INIT, value: 31, goesTo: { bot: 92 } },
		{
			action: GIVE,
			from: { bot: 44 },
			lowTo: { bot: 16 },
			highTo: { bot: 91 },
		},
		{
			action: GIVE,
			from: { bot: 172 },
			lowTo: { bot: 84 },
			highTo: { bot: 27 },
		},
		{
			action: GIVE,
			from: { bot: 39 },
			lowTo: { bot: 44 },
			highTo: { bot: 154 },
		},
		{
			action: GIVE,
			from: { bot: 170 },
			lowTo: { bot: 95 },
			highTo: { bot: 146 },
		},
		{
			action: GIVE,
			from: { bot: 98 },
			lowTo: { bot: 193 },
			highTo: { bot: 17 },
		},
		{
			action: GIVE,
			from: { bot: 4 },
			lowTo: { bot: 26 },
			highTo: { bot: 109 },
		},
		{
			action: GIVE,
			from: { bot: 197 },
			lowTo: { bot: 71 },
			highTo: { bot: 106 },
		},
		{
			action: GIVE,
			from: { bot: 132 },
			lowTo: { bot: 161 },
			highTo: { bot: 181 },
		},
		{
			action: GIVE,
			from: { bot: 54 },
			lowTo: { bot: 156 },
			highTo: { bot: 148 },
		},
		{
			action: GIVE,
			from: { bot: 140 },
			lowTo: { bot: 0 },
			highTo: { bot: 25 },
		},
		{
			action: GIVE,
			from: { bot: 59 },
			lowTo: { output: 10 },
			highTo: { bot: 93 },
		},
		{
			action: GIVE,
			from: { bot: 206 },
			lowTo: { bot: 2 },
			highTo: { bot: 200 },
		},
		{
			action: GIVE,
			from: { bot: 5 },
			lowTo: { bot: 201 },
			highTo: { bot: 173 },
		},
		{
			action: GIVE,
			from: { bot: 81 },
			lowTo: { bot: 24 },
			highTo: { bot: 30 },
		},
		{
			action: GIVE,
			from: { bot: 33 },
			lowTo: { bot: 100 },
			highTo: { bot: 113 },
		},
		{
			action: GIVE,
			from: { bot: 73 },
			lowTo: { bot: 60 },
			highTo: { bot: 129 },
		},
		{
			action: GIVE,
			from: { bot: 43 },
			lowTo: { output: 14 },
			highTo: { bot: 204 },
		},
		{
			action: GIVE,
			from: { bot: 143 },
			lowTo: { bot: 176 },
			highTo: { bot: 196 },
		},
		{
			action: GIVE,
			from: { bot: 182 },
			lowTo: { bot: 70 },
			highTo: { bot: 76 },
		},
		{
			action: GIVE,
			from: { bot: 139 },
			lowTo: { bot: 117 },
			highTo: { bot: 180 },
		},
		{
			action: GIVE,
			from: { bot: 31 },
			lowTo: { bot: 131 },
			highTo: { bot: 137 },
		},
		{
			action: GIVE,
			from: { bot: 179 },
			lowTo: { bot: 31 },
			highTo: { bot: 28 },
		},
		{
			action: GIVE,
			from: { bot: 74 },
			lowTo: { bot: 29 },
			highTo: { bot: 160 },
		},
		{
			action: GIVE,
			from: { bot: 7 },
			lowTo: { bot: 191 },
			highTo: { bot: 21 },
		},
		{
			action: GIVE,
			from: { bot: 83 },
			lowTo: { bot: 165 },
			highTo: { bot: 116 },
		},
		{
			action: GIVE,
			from: { bot: 142 },
			lowTo: { bot: 144 },
			highTo: { bot: 107 },
		},
		{
			action: GIVE,
			from: { bot: 187 },
			lowTo: { bot: 129 },
			highTo: { bot: 68 },
		},
		{ action: INIT, value: 61, goesTo: { bot: 32 } },
		{
			action: GIVE,
			from: { bot: 32 },
			lowTo: { bot: 72 },
			highTo: { bot: 53 },
		},
		{
			action: GIVE,
			from: { bot: 53 },
			lowTo: { bot: 121 },
			highTo: { bot: 199 },
		},
		{
			action: GIVE,
			from: { bot: 79 },
			lowTo: { bot: 143 },
			highTo: { bot: 196 },
		},
		{
			action: GIVE,
			from: { bot: 0 },
			lowTo: { bot: 92 },
			highTo: { bot: 194 },
		},
		{
			action: GIVE,
			from: { bot: 8 },
			lowTo: { bot: 56 },
			highTo: { bot: 209 },
		},
		{ action: INIT, value: 43, goesTo: { bot: 72 } },
		{
			action: GIVE,
			from: { bot: 95 },
			lowTo: { output: 18 },
			highTo: { bot: 112 },
		},
		{
			action: GIVE,
			from: { bot: 104 },
			lowTo: { bot: 41 },
			highTo: { bot: 185 },
		},
		{
			action: GIVE,
			from: { bot: 198 },
			lowTo: { bot: 103 },
			highTo: { bot: 48 },
		},
		{
			action: GIVE,
			from: { bot: 17 },
			lowTo: { bot: 69 },
			highTo: { bot: 156 },
		},
		{
			action: GIVE,
			from: { bot: 138 },
			lowTo: { output: 0 },
			highTo: { bot: 77 },
		},
		{
			action: GIVE,
			from: { bot: 76 },
			lowTo: { bot: 127 },
			highTo: { bot: 164 },
		},
		{
			action: GIVE,
			from: { bot: 110 },
			lowTo: { bot: 206 },
			highTo: { bot: 60 },
		},
		{
			action: GIVE,
			from: { bot: 60 },
			lowTo: { bot: 200 },
			highTo: { bot: 141 },
		},
		{
			action: GIVE,
			from: { bot: 134 },
			lowTo: { bot: 67 },
			highTo: { bot: 7 },
		},
		{
			action: GIVE,
			from: { bot: 90 },
			lowTo: { bot: 12 },
			highTo: { bot: 192 },
		},
		{
			action: GIVE,
			from: { bot: 208 },
			lowTo: { bot: 155 },
			highTo: { bot: 182 },
		},
		{
			action: GIVE,
			from: { bot: 87 },
			lowTo: { bot: 28 },
			highTo: { bot: 195 },
		},
		{
			action: GIVE,
			from: { bot: 108 },
			lowTo: { bot: 53 },
			highTo: { bot: 186 },
		},
		{
			action: GIVE,
			from: { bot: 150 },
			lowTo: { bot: 154 },
			highTo: { bot: 56 },
		},
		{
			action: GIVE,
			from: { bot: 204 },
			lowTo: { output: 17 },
			highTo: { bot: 58 },
		},
		{
			action: GIVE,
			from: { bot: 174 },
			lowTo: { bot: 138 },
			highTo: { bot: 67 },
		},
		{
			action: GIVE,
			from: { bot: 195 },
			lowTo: { bot: 147 },
			highTo: { bot: 81 },
		},
		{
			action: GIVE,
			from: { bot: 24 },
			lowTo: { bot: 146 },
			highTo: { bot: 3 },
		},
		{
			action: GIVE,
			from: { bot: 12 },
			lowTo: { bot: 119 },
			highTo: { bot: 9 },
		},
		{ action: INIT, value: 37, goesTo: { bot: 35 } },
		{
			action: GIVE,
			from: { bot: 137 },
			lowTo: { bot: 151 },
			highTo: { bot: 170 },
		},
		{
			action: GIVE,
			from: { bot: 1 },
			lowTo: { output: 2 },
			highTo: { bot: 22 },
		},
		{
			action: GIVE,
			from: { bot: 63 },
			lowTo: { bot: 150 },
			highTo: { bot: 8 },
		},
		{
			action: GIVE,
			from: { bot: 133 },
			lowTo: { bot: 140 },
			highTo: { bot: 124 },
		},
		{
			action: GIVE,
			from: { bot: 154 },
			lowTo: { bot: 91 },
			highTo: { bot: 110 },
		},
		{
			action: GIVE,
			from: { bot: 145 },
			lowTo: { bot: 47 },
			highTo: { bot: 18 },
		},
		{
			action: GIVE,
			from: { bot: 109 },
			lowTo: { bot: 159 },
			highTo: { bot: 82 },
		},
		{
			action: GIVE,
			from: { bot: 202 },
			lowTo: { bot: 116 },
			highTo: { bot: 37 },
		},
		{
			action: GIVE,
			from: { bot: 168 },
			lowTo: { bot: 133 },
			highTo: { bot: 177 },
		},
		{
			action: GIVE,
			from: { bot: 193 },
			lowTo: { bot: 93 },
			highTo: { bot: 69 },
		},
		{
			action: GIVE,
			from: { bot: 191 },
			lowTo: { output: 16 },
			highTo: { bot: 21 },
		},
		{
			action: GIVE,
			from: { bot: 135 },
			lowTo: { bot: 82 },
			highTo: { bot: 163 },
		},
		{
			action: GIVE,
			from: { bot: 130 },
			lowTo: { bot: 102 },
			highTo: { bot: 114 },
		},
		{
			action: GIVE,
			from: { bot: 26 },
			lowTo: { bot: 208 },
			highTo: { bot: 159 },
		},
		{
			action: GIVE,
			from: { bot: 152 },
			lowTo: { bot: 22 },
			highTo: { bot: 31 },
		},
		{
			action: GIVE,
			from: { bot: 118 },
			lowTo: { bot: 136 },
			highTo: { bot: 144 },
		},
		{
			action: GIVE,
			from: { bot: 149 },
			lowTo: { bot: 17 },
			highTo: { bot: 54 },
		},
		{
			action: GIVE,
			from: { bot: 64 },
			lowTo: { bot: 164 },
			highTo: { bot: 119 },
		},
		{
			action: GIVE,
			from: { bot: 120 },
			lowTo: { bot: 64 },
			highTo: { bot: 12 },
		},
		{
			action: GIVE,
			from: { bot: 180 },
			lowTo: { bot: 188 },
			highTo: { bot: 130 },
		},
		{
			action: GIVE,
			from: { bot: 203 },
			lowTo: { bot: 204 },
			highTo: { bot: 125 },
		},
		{
			action: GIVE,
			from: { bot: 3 },
			lowTo: { bot: 46 },
			highTo: { bot: 104 },
		},
		{
			action: GIVE,
			from: { bot: 114 },
			lowTo: { bot: 205 },
			highTo: { bot: 79 },
		},
		{
			action: GIVE,
			from: { bot: 25 },
			lowTo: { bot: 194 },
			highTo: { bot: 20 },
		},
		{
			action: GIVE,
			from: { bot: 65 },
			lowTo: { bot: 181 },
			highTo: { bot: 118 },
		},
		{
			action: GIVE,
			from: { bot: 169 },
			lowTo: { bot: 192 },
			highTo: { bot: 117 },
		},
		{
			action: GIVE,
			from: { bot: 51 },
			lowTo: { output: 8 },
			highTo: { bot: 50 },
		},
		{
			action: GIVE,
			from: { bot: 41 },
			lowTo: { bot: 50 },
			highTo: { bot: 145 },
		},
		{
			action: GIVE,
			from: { bot: 20 },
			lowTo: { bot: 23 },
			highTo: { bot: 10 },
		},
		{
			action: GIVE,
			from: { bot: 106 },
			lowTo: { bot: 96 },
			highTo: { bot: 126 },
		},
		{
			action: GIVE,
			from: { bot: 23 },
			lowTo: { bot: 5 },
			highTo: { bot: 6 },
		},
		{ action: INIT, value: 11, goesTo: { bot: 43 } },
		{ action: INIT, value: 47, goesTo: { bot: 189 } },
		{ action: INIT, value: 5, goesTo: { bot: 115 } },
		{
			action: GIVE,
			from: { bot: 46 },
			lowTo: { bot: 51 },
			highTo: { bot: 41 },
		},
		{
			action: GIVE,
			from: { bot: 115 },
			lowTo: { bot: 43 },
			highTo: { bot: 203 },
		},
		{
			action: GIVE,
			from: { bot: 209 },
			lowTo: { bot: 73 },
			highTo: { bot: 187 },
		},
		{
			action: GIVE,
			from: { bot: 16 },
			lowTo: { bot: 113 },
			highTo: { bot: 62 },
		},
		{
			action: GIVE,
			from: { bot: 101 },
			lowTo: { bot: 174 },
			highTo: { bot: 134 },
		},
		{
			action: GIVE,
			from: { bot: 167 },
			lowTo: { output: 20 },
			highTo: { bot: 158 },
		},
		{ action: INIT, value: 3, goesTo: { bot: 133 } },
		{
			action: GIVE,
			from: { bot: 184 },
			lowTo: { bot: 125 },
			highTo: { bot: 100 },
		},
		{
			action: GIVE,
			from: { bot: 155 },
			lowTo: { bot: 166 },
			highTo: { bot: 70 },
		},
		{
			action: GIVE,
			from: { bot: 88 },
			lowTo: { bot: 81 },
			highTo: { bot: 84 },
		},
		{ action: INIT, value: 19, goesTo: { bot: 0 } },
		{
			action: GIVE,
			from: { bot: 171 },
			lowTo: { bot: 36 },
			highTo: { bot: 45 },
		},
		{
			action: GIVE,
			from: { bot: 186 },
			lowTo: { bot: 199 },
			highTo: { bot: 97 },
		},
		{
			action: GIVE,
			from: { bot: 111 },
			lowTo: { bot: 209 },
			highTo: { bot: 85 },
		},
		{
			action: GIVE,
			from: { bot: 22 },
			lowTo: { output: 4 },
			highTo: { bot: 131 },
		},
		{
			action: GIVE,
			from: { bot: 166 },
			lowTo: { bot: 132 },
			highTo: { bot: 65 },
		},
		{
			action: GIVE,
			from: { bot: 6 },
			lowTo: { bot: 173 },
			highTo: { bot: 52 },
		},
		{
			action: GIVE,
			from: { bot: 75 },
			lowTo: { bot: 104 },
			highTo: { bot: 29 },
		},
		{
			action: GIVE,
			from: { bot: 91 },
			lowTo: { bot: 62 },
			highTo: { bot: 206 },
		},
		{
			action: GIVE,
			from: { bot: 164 },
			lowTo: { bot: 142 },
			highTo: { bot: 38 },
		},
		{
			action: GIVE,
			from: { bot: 15 },
			lowTo: { bot: 160 },
			highTo: { bot: 197 },
		},
		{
			action: GIVE,
			from: { bot: 66 },
			lowTo: { bot: 198 },
			highTo: { bot: 188 },
		},
		{
			action: GIVE,
			from: { bot: 199 },
			lowTo: { bot: 184 },
			highTo: { bot: 33 },
		},
		{
			action: GIVE,
			from: { bot: 122 },
			lowTo: { bot: 55 },
			highTo: { bot: 5 },
		},
		{
			action: GIVE,
			from: { bot: 68 },
			lowTo: { bot: 40 },
			highTo: { bot: 143 },
		},
		{
			action: GIVE,
			from: { bot: 128 },
			lowTo: { bot: 4 },
			highTo: { bot: 94 },
		},
		{
			action: GIVE,
			from: { bot: 27 },
			lowTo: { bot: 13 },
			highTo: { bot: 78 },
		},
		{
			action: GIVE,
			from: { bot: 34 },
			lowTo: { bot: 195 },
			highTo: { bot: 88 },
		},
		{
			action: GIVE,
			from: { bot: 94 },
			lowTo: { bot: 109 },
			highTo: { bot: 135 },
		},
		{
			action: GIVE,
			from: { bot: 158 },
			lowTo: { output: 3 },
			highTo: { bot: 138 },
		},
		{
			action: GIVE,
			from: { bot: 47 },
			lowTo: { output: 15 },
			highTo: { bot: 59 },
		},
		{
			action: GIVE,
			from: { bot: 163 },
			lowTo: { bot: 120 },
			highTo: { bot: 90 },
		},
		{
			action: GIVE,
			from: { bot: 48 },
			lowTo: { bot: 111 },
			highTo: { bot: 102 },
		},
		{
			action: GIVE,
			from: { bot: 40 },
			lowTo: { bot: 207 },
			highTo: { bot: 176 },
		},
		{
			action: GIVE,
			from: { bot: 144 },
			lowTo: { bot: 153 },
			highTo: { bot: 39 },
		},
		{
			action: GIVE,
			from: { bot: 201 },
			lowTo: { bot: 162 },
			highTo: { bot: 83 },
		},
		{
			action: GIVE,
			from: { bot: 72 },
			lowTo: { bot: 115 },
			highTo: { bot: 121 },
		},
		{
			action: GIVE,
			from: { bot: 156 },
			lowTo: { bot: 19 },
			highTo: { bot: 101 },
		},
		{
			action: GIVE,
			from: { bot: 185 },
			lowTo: { bot: 145 },
			highTo: { bot: 183 },
		},
		{
			action: GIVE,
			from: { bot: 103 },
			lowTo: { bot: 8 },
			highTo: { bot: 111 },
		},
		{
			action: GIVE,
			from: { bot: 192 },
			lowTo: { bot: 9 },
			highTo: { bot: 66 },
		},
		{ action: INIT, value: 71, goesTo: { bot: 140 } },
		{
			action: GIVE,
			from: { bot: 205 },
			lowTo: { bot: 68 },
			highTo: { bot: 79 },
		},
		{
			action: GIVE,
			from: { bot: 151 },
			lowTo: { output: 11 },
			highTo: { bot: 95 },
		},
		{
			action: GIVE,
			from: { bot: 153 },
			lowTo: { bot: 97 },
			highTo: { bot: 44 },
		},
		{
			action: GIVE,
			from: { bot: 105 },
			lowTo: { bot: 15 },
			highTo: { bot: 175 },
		},
		{
			action: GIVE,
			from: { bot: 11 },
			lowTo: { bot: 183 },
			highTo: { bot: 86 },
		},
		{
			action: GIVE,
			from: { bot: 160 },
			lowTo: { bot: 11 },
			highTo: { bot: 71 },
		},
		{
			action: GIVE,
			from: { bot: 56 },
			lowTo: { bot: 110 },
			highTo: { bot: 73 },
		},
		{
			action: GIVE,
			from: { bot: 207 },
			lowTo: { bot: 172 },
			highTo: { bot: 89 },
		},
		{
			action: GIVE,
			from: { bot: 181 },
			lowTo: { bot: 108 },
			highTo: { bot: 136 },
		},
		{
			action: GIVE,
			from: { bot: 175 },
			lowTo: { bot: 197 },
			highTo: { bot: 106 },
		},
		{
			action: GIVE,
			from: { bot: 69 },
			lowTo: { bot: 167 },
			highTo: { bot: 19 },
		},
		{
			action: GIVE,
			from: { bot: 58 },
			lowTo: { output: 9 },
			highTo: { bot: 1 },
		},
		{
			action: GIVE,
			from: { bot: 78 },
			lowTo: { bot: 74 },
			highTo: { bot: 15 },
		},
		{
			action: GIVE,
			from: { bot: 21 },
			lowTo: { output: 12 },
			highTo: { output: 19 },
		},
		{
			action: GIVE,
			from: { bot: 190 },
			lowTo: { bot: 168 },
			highTo: { bot: 177 },
		},
		{ action: INIT, value: 29, goesTo: { bot: 190 } },
		{
			action: GIVE,
			from: { bot: 107 },
			lowTo: { bot: 39 },
			highTo: { bot: 150 },
		},
		{
			action: GIVE,
			from: { bot: 61 },
			lowTo: { bot: 63 },
			highTo: { bot: 103 },
		},
		{
			action: GIVE,
			from: { bot: 52 },
			lowTo: { bot: 202 },
			highTo: { bot: 37 },
		},
		{ action: INIT, value: 53, goesTo: { bot: 168 } },
		{
			action: GIVE,
			from: { bot: 30 },
			lowTo: { bot: 3 },
			highTo: { bot: 75 },
		},
		{
			action: GIVE,
			from: { bot: 116 },
			lowTo: { bot: 123 },
			highTo: { bot: 42 },
		},
		{
			action: GIVE,
			from: { bot: 85 },
			lowTo: { bot: 187 },
			highTo: { bot: 205 },
		},
		{
			action: GIVE,
			from: { bot: 99 },
			lowTo: { bot: 94 },
			highTo: { bot: 162 },
		},
		{
			action: GIVE,
			from: { bot: 126 },
			lowTo: { bot: 54 },
			highTo: { bot: 148 },
		},
		{
			action: GIVE,
			from: { bot: 19 },
			lowTo: { bot: 158 },
			highTo: { bot: 174 },
		},
		{
			action: GIVE,
			from: { bot: 82 },
			lowTo: { bot: 49 },
			highTo: { bot: 120 },
		},
		{
			action: GIVE,
			from: { bot: 42 },
			lowTo: { bot: 169 },
			highTo: { bot: 139 },
		},
		{ action: INIT, value: 41, goesTo: { bot: 190 } },
		{
			action: GIVE,
			from: { bot: 188 },
			lowTo: { bot: 48 },
			highTo: { bot: 130 },
		},
		{
			action: GIVE,
			from: { bot: 113 },
			lowTo: { bot: 14 },
			highTo: { bot: 157 },
		},
		{
			action: GIVE,
			from: { bot: 177 },
			lowTo: { bot: 124 },
			highTo: { bot: 80 },
		},
		{
			action: GIVE,
			from: { bot: 18 },
			lowTo: { bot: 59 },
			highTo: { bot: 193 },
		},
		{
			action: GIVE,
			from: { bot: 96 },
			lowTo: { bot: 149 },
			highTo: { bot: 126 },
		},
		{
			action: GIVE,
			from: { bot: 62 },
			lowTo: { bot: 157 },
			highTo: { bot: 2 },
		},
		{
			action: GIVE,
			from: { bot: 45 },
			lowTo: { bot: 105 },
			highTo: { bot: 175 },
		},
		{
			action: GIVE,
			from: { bot: 2 },
			lowTo: { bot: 87 },
			highTo: { bot: 34 },
		},
		{
			action: GIVE,
			from: { bot: 147 },
			lowTo: { bot: 170 },
			highTo: { bot: 24 },
		},
		{
			action: GIVE,
			from: { bot: 70 },
			lowTo: { bot: 65 },
			highTo: { bot: 127 },
		},
		{
			action: GIVE,
			from: { bot: 162 },
			lowTo: { bot: 135 },
			highTo: { bot: 165 },
		},
		{
			action: GIVE,
			from: { bot: 117 },
			lowTo: { bot: 66 },
			highTo: { bot: 180 },
		},
		{
			action: GIVE,
			from: { bot: 100 },
			lowTo: { bot: 57 },
			highTo: { bot: 14 },
		},
		{
			action: GIVE,
			from: { bot: 57 },
			lowTo: { bot: 1 },
			highTo: { bot: 152 },
		},
		{
			action: GIVE,
			from: { bot: 121 },
			lowTo: { bot: 203 },
			highTo: { bot: 184 },
		},
		{
			action: GIVE,
			from: { bot: 10 },
			lowTo: { bot: 6 },
			highTo: { bot: 52 },
		},
		{
			action: GIVE,
			from: { bot: 84 },
			lowTo: { bot: 30 },
			highTo: { bot: 13 },
		},
		{ action: INIT, value: 7, goesTo: { bot: 166 } },
		{
			action: GIVE,
			from: { bot: 136 },
			lowTo: { bot: 186 },
			highTo: { bot: 153 },
		},
		{
			action: GIVE,
			from: { bot: 161 },
			lowTo: { bot: 32 },
			highTo: { bot: 108 },
		},
		{
			action: GIVE,
			from: { bot: 102 },
			lowTo: { bot: 85 },
			highTo: { bot: 114 },
		},
		{
			action: GIVE,
			from: { bot: 80 },
			lowTo: { bot: 20 },
			highTo: { bot: 10 },
		},
		{
			action: GIVE,
			from: { bot: 200 },
			lowTo: { bot: 34 },
			highTo: { bot: 178 },
		},
		{
			action: GIVE,
			from: { bot: 119 },
			lowTo: { bot: 38 },
			highTo: { bot: 61 },
		},
		{
			action: GIVE,
			from: { bot: 28 },
			lowTo: { bot: 137 },
			highTo: { bot: 147 },
		},
		{
			action: GIVE,
			from: { bot: 35 },
			lowTo: { bot: 128 },
			highTo: { bot: 99 },
		},
		{ action: INIT, value: 67, goesTo: { bot: 132 } },
		{
			action: GIVE,
			from: { bot: 146 },
			lowTo: { bot: 112 },
			highTo: { bot: 46 },
		},
		{
			action: GIVE,
			from: { bot: 194 },
			lowTo: { bot: 122 },
			highTo: { bot: 23 },
		},
		{ action: INIT, value: 73, goesTo: { bot: 26 } },
		{
			action: GIVE,
			from: { bot: 183 },
			lowTo: { bot: 18 },
			highTo: { bot: 98 },
		},
	],
};
