const INSTRUCTIONS = [
    { type: 'rect', size: [1, 1] },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'rect', size: [1, 1] },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'rect', size: [1, 1] },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'rect', size: [1, 1] },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'rect', size: [1, 1] },
    { type: 'shift_row', row: 0, by: 2 },
    { type: 'rect', size: [1, 1] },
    { type: 'shift_row', row: 0, by: 2 },
    { type: 'rect', size: [1, 1] },
    { type: 'shift_row', row: 0, by: 3 },
    { type: 'rect', size: [1, 1] },
    { type: 'shift_row', row: 0, by: 3 },
    { type: 'rect', size: [2, 1] },
    { type: 'shift_row', row: 0, by: 2 },
    { type: 'rect', size: [1, 1] },
    { type: 'shift_row', row: 0, by: 3 },
    { type: 'rect', size: [2, 1] },
    { type: 'shift_row', row: 0, by: 2 },
    { type: 'rect', size: [1, 1] },
    { type: 'shift_row', row: 0, by: 3 },
    { type: 'rect', size: [2, 1] },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'rect', size: [4, 1] },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [4, 1] },
    { type: 'shift_row', row: 0, by: 10 },
    { type: 'shift_col', col: 5, by: 2 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [9, 1] },
    { type: 'shift_row', row: 2, by: 5 },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [4, 1] },
    { type: 'shift_row', row: 2, by: 5 },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [4, 1] },
    { type: 'shift_col', col: 40, by: 1 },
    { type: 'shift_col', col: 27, by: 1 },
    { type: 'shift_col', col: 22, by: 1 },
    { type: 'shift_col', col: 17, by: 1 },
    { type: 'shift_col', col: 12, by: 1 },
    { type: 'shift_col', col: 7, by: 1 },
    { type: 'shift_col', col: 2, by: 1 },
    { type: 'shift_row', row: 2, by: 5 },
    { type: 'shift_row', row: 1, by: 3 },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'rect', size: [1, 3] },
    { type: 'shift_row', row: 2, by: 10 },
    { type: 'shift_row', row: 1, by: 7 },
    { type: 'shift_row', row: 0, by: 2 },
    { type: 'shift_col', col: 3, by: 2 },
    { type: 'shift_col', col: 2, by: 1 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [4, 1] },
    { type: 'shift_row', row: 2, by: 5 },
    { type: 'shift_row', row: 1, by: 3 },
    { type: 'shift_row', row: 0, by: 3 },
    { type: 'rect', size: [1, 3] },
    { type: 'shift_col', col: 45, by: 1 },
    { type: 'shift_row', row: 2, by: 7 },
    { type: 'shift_row', row: 1, by: 10 },
    { type: 'shift_row', row: 0, by: 2 },
    { type: 'shift_col', col: 3, by: 1 },
    { type: 'shift_col', col: 2, by: 2 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [4, 1] },
    { type: 'shift_row', row: 2, by: 13 },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'shift_col', col: 3, by: 1 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [4, 1] },
    { type: 'shift_row', row: 3, by: 10 },
    { type: 'shift_row', row: 2, by: 10 },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'shift_col', col: 3, by: 1 },
    { type: 'shift_col', col: 2, by: 1 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [4, 1] },
    { type: 'shift_row', row: 3, by: 8 },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'shift_col', col: 3, by: 1 },
    { type: 'shift_col', col: 2, by: 1 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [4, 1] },
    { type: 'shift_row', row: 3, by: 17 },
    { type: 'shift_row', row: 2, by: 20 },
    { type: 'shift_row', row: 0, by: 15 },
    { type: 'shift_col', col: 13, by: 1 },
    { type: 'shift_col', col: 12, by: 3 },
    { type: 'shift_col', col: 10, by: 1 },
    { type: 'shift_col', col: 8, by: 1 },
    { type: 'shift_col', col: 7, by: 2 },
    { type: 'shift_col', col: 6, by: 1 },
    { type: 'shift_col', col: 5, by: 1 },
    { type: 'shift_col', col: 3, by: 1 },
    { type: 'shift_col', col: 2, by: 2 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [14, 1] },
    { type: 'shift_row', row: 1, by: 47 },
    { type: 'shift_col', col: 9, by: 1 },
    { type: 'shift_col', col: 4, by: 1 },
    { type: 'shift_row', row: 3, by: 3 },
    { type: 'shift_row', row: 2, by: 10 },
    { type: 'shift_row', row: 1, by: 8 },
    { type: 'shift_row', row: 0, by: 5 },
    { type: 'shift_col', col: 2, by: 2 },
    { type: 'shift_col', col: 0, by: 2 },
    { type: 'rect', size: [3, 2] },
    { type: 'shift_row', row: 3, by: 12 },
    { type: 'shift_row', row: 2, by: 10 },
    { type: 'shift_row', row: 0, by: 10 },
    { type: 'shift_col', col: 8, by: 1 },
    { type: 'shift_col', col: 7, by: 3 },
    { type: 'shift_col', col: 5, by: 1 },
    { type: 'shift_col', col: 3, by: 1 },
    { type: 'shift_col', col: 2, by: 1 },
    { type: 'shift_col', col: 1, by: 1 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [9, 1] },
    { type: 'shift_row', row: 0, by: 20 },
    { type: 'shift_col', col: 46, by: 1 },
    { type: 'shift_row', row: 4, by: 17 },
    { type: 'shift_row', row: 3, by: 10 },
    { type: 'shift_row', row: 2, by: 10 },
    { type: 'shift_row', row: 1, by: 5 },
    { type: 'shift_col', col: 8, by: 1 },
    { type: 'shift_col', col: 7, by: 1 },
    { type: 'shift_col', col: 6, by: 1 },
    { type: 'shift_col', col: 5, by: 1 },
    { type: 'shift_col', col: 3, by: 1 },
    { type: 'shift_col', col: 2, by: 2 },
    { type: 'shift_col', col: 1, by: 1 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [9, 1] },
    { type: 'shift_col', col: 32, by: 4 },
    { type: 'shift_row', row: 4, by: 33 },
    { type: 'shift_row', row: 3, by: 5 },
    { type: 'shift_row', row: 2, by: 15 },
    { type: 'shift_row', row: 0, by: 15 },
    { type: 'shift_col', col: 13, by: 1 },
    { type: 'shift_col', col: 12, by: 3 },
    { type: 'shift_col', col: 10, by: 1 },
    { type: 'shift_col', col: 8, by: 1 },
    { type: 'shift_col', col: 7, by: 2 },
    { type: 'shift_col', col: 6, by: 1 },
    { type: 'shift_col', col: 5, by: 1 },
    { type: 'shift_col', col: 3, by: 1 },
    { type: 'shift_col', col: 2, by: 1 },
    { type: 'shift_col', col: 1, by: 1 },
    { type: 'shift_col', col: 0, by: 1 },
    { type: 'rect', size: [14, 1] },
    { type: 'shift_col', col: 39, by: 3 },
    { type: 'shift_col', col: 35, by: 4 },
    { type: 'shift_col', col: 20, by: 4 },
    { type: 'shift_col', col: 19, by: 3 },
    { type: 'shift_col', col: 10, by: 4 },
    { type: 'shift_col', col: 9, by: 3 },
    { type: 'shift_col', col: 8, by: 3 },
    { type: 'shift_col', col: 5, by: 4 },
    { type: 'shift_col', col: 4, by: 3 },
    { type: 'shift_row', row: 5, by: 5 },
    { type: 'shift_row', row: 4, by: 5 },
    { type: 'shift_row', row: 3, by: 33 },
    { type: 'shift_row', row: 1, by: 30 },
    { type: 'shift_col', col: 48, by: 1 },
    { type: 'shift_col', col: 47, by: 5 },
    { type: 'shift_col', col: 46, by: 5 },
    { type: 'shift_col', col: 45, by: 1 },
    { type: 'shift_col', col: 43, by: 1 },
    { type: 'shift_col', col: 38, by: 3 },
    { type: 'shift_col', col: 37, by: 3 },
    { type: 'shift_col', col: 36, by: 5 },
    { type: 'shift_col', col: 35, by: 1 },
    { type: 'shift_col', col: 33, by: 1 },
    { type: 'shift_col', col: 32, by: 5 },
    { type: 'shift_col', col: 31, by: 5 },
    { type: 'shift_col', col: 30, by: 1 },
    { type: 'shift_col', col: 23, by: 4 },
    { type: 'shift_col', col: 22, by: 3 },
    { type: 'shift_col', col: 21, by: 3 },
    { type: 'shift_col', col: 20, by: 1 },
    { type: 'shift_col', col: 12, by: 2 },
    { type: 'shift_col', col: 11, by: 2 },
    { type: 'shift_col', col: 3, by: 5 },
    { type: 'shift_col', col: 2, by: 5 },
    { type: 'shift_col', col: 1, by: 3 },
    { type: 'shift_col', col: 0, by: 4 },
];

module.exports = {
    sampleInput: {
        screenSize: [7, 3],
        instructions: [
            { type: 'rect', size: [3, 2] },
            { type: 'shift_col', col: 1, by: 1 },
            { type: 'shift_row', row: 0, by: 4 },
            { type: 'shift_col', col: 1, by: 1 },
            // Creates:
            //
            //   .#..#.#
            //   #.#....
            //   .#.....
            //
            // 6 pixels are lit
        ],
    },
    input: {
        screenSize: [50, 6],
        instructions: INSTRUCTIONS,
    },
};
